### ISSUE TITLE
PDFBox issue

### ISSUE THREAD

**Issue by mmluk** [tabulapdf/tabula-java#101]
Hey guys,

Finding that this is an excellent tool, but for some tables that work fine on the GUI/app version but when running from command line, I get these:

Aug 26, 2016 6:59:25 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: BDC
Aug 26, 2016 6:59:25 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: i
Aug 26, 2016 6:59:26 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: EMC
Aug 26, 2016 6:59:26 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: BMC

And then all the text from the table is badly formed and in fact missing the majority of the text, using:
java -jar tabula-0.9.0-SNAPSHOT-jar-with-dependencies.jar con030910.pdf -p 7  -d -r -u -f TSV 

Any ideas? 
Cheers,
Mike

**Comment by mmluk** [comment]
I had some weird unrelated issue reading in the output.

**Comment by jeremybmerrill** [comment]
Glad to hear you figured it out. Those INFO lines are just random info that, for whatever reason, we haven't managed to mute. They're not errors.
