### ISSUE TITLE
How to import source in Eclipse and run project?

### ISSUE THREAD

**Issue by roondal** [tabulapdf/tabula-java#103]
I am import source as Maven project, but dont run.
How to import source in Eclipse and run project?

**Comment by jazzido** [comment]
Hi @roondal,

`tabula-java` is a library. There's a command line application in `CommandLineApp` that has a `main` method that you can run.

**Comment by vishnu41** [comment]
@jazzido can you elaborate your answer. 
1. Where is CommandLineApp? 
2. How to import src in Eclipse and run ?
