### ISSUE TITLE
Exception in thread "main" java.util.NoSuchElementException

### ISSUE THREAD

**Issue by xeonhh** [tabulapdf/tabula-java#105]
When I run the tool in command line, it prompted the following error, and generated an empty csv file. Could you please help to investigate?

 -p all -a 617.684,73.259,776.103,315.722 -o pdf01.csv test_pdf2.pdf

Exception in thread "main" java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(Unknown Source)
        at java.util.Collections.min(Unknown Source)
        at technology.tabula.Page.getArea(Page.java:67)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:14
7)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)

**Comment by jazzido** [comment]
Hi @xeonhh,

Can you send us the PDF, so we can examine the issue for ourselves?

You can send the PDF any of the following three ways:

1. send a link, if the PDF is accessible over the internet
2. attach it via Github's web Issues interface, if the document is not sensitive. (You must use the web interface. If you attempt to attach it to an email reply to GitHub, it will not be sent.)
3. send it directly by email to me (or another Tabula collaborator), using the email address in my profile. If the document is sensitive, please say so.

**Comment by jeremybmerrill** [comment]
I think this is the same as https://github.com/tabulapdf/tabula/issues/573

**Comment by jeremybmerrill** [comment]
closed via #131; fix will be in next release
