### ISSUE TITLE
How to use command line in Windows?

### ISSUE THREAD

**Issue by gosforth** [tabulapdf/tabula-java#108]
Great tool. But I want command line instead of web edition.
So, I download Windows version from http://tabula.technology/ what's the command to process pdf?

It should be something like:
`java -jar tabula.jar -a 71.0,71.0,100.07,539.945 --out test.pdf`
But what exactly? Given example 
`java -jar ./target/tabula-0.9.0-jar-with-dependencies.jar -p all -a $y1,$x1,$y2,$x2 -o $csvfile $filename`

Dos not work. There is no tabula-0.9.0-jar-with-dependencies.jar file there....

**Comment by criztovyl** [comment]
There is an `tabula.exe` in there, I think it should do the job. Try `tabula --help` in extracted directory.

**Comment by criztovyl** [comment]
Seems like the `exe` is only a local web-based thingy.  
There is no `with-dependencies` JAR because you didn't built from source (that's okay :D), in your ZIP the `tabula. jar` is the `with-dependencies` :)
So, try that:

     java -jar tabula.jar -p all -a $y1,$x1,$y2,$x2 -o $csvfile $filename

**Comment by criztovyl** [comment]
The ZIPs from tabula.technology do not contain the CLI interface.

You have to download the Release from GitHub, there also is the `with-dependencies.jar`: https://github.com/tabulapdf/tabula-java/releases/latest

**Comment by gosforth** [comment]
Thank you.

**Comment by criztovyl** [comment]
You should close the issue if it does the job :)
