### ISSUE TITLE
Problem with two lines cells in tables

### ISSUE THREAD

**Issue by gosforth** [tabulapdf/tabula-java#109]
I see tool has problem with rows in tables where row has two lines. Something:

first cell |second cell | third cell
               with two lines

CSV it will produce will be:

first cell, second cell, third cell
with two lines

**Comment by jeremybmerrill** [comment]
In "Stream" mode, this is expected behavior. Stream mode is unable to distinguish multi-line cells from separate rows. If your PDF has lines separating each cell, you can try selecting the Lattice mode, which handles multi-line rows as you expect.
