### ISSUE TITLE
tabula-java CLI not extracting table data

### ISSUE THREAD

**Issue by psankar** [tabulapdf/tabula-java#118]
When I execute `java -jar tabula-0.9.0-SNAPSHOT-jar-with-dependencies.jar -r file.pdf`, I get the following printed on the console.

```
Nov 07, 2016 11:41:08 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: BDC
Nov 07, 2016 11:41:08 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: EMC
``` 

However, when I use the tabula-java GUI and ask it to auto-select tables, all the tabular data in the PDF is selected correctly. I can give a scrubbed pdf if needed. I have tried without the "-r" spreadsheet algorithm too and I get the same INFO messages. But none of the other tabular contents that I want (and identified by the GUI tool) are extracted.

**Comment by jeremybmerrill** [comment]
You probably want to add the `-g` flag to enable the autoselection (like in the GUI). 

Those info messages are expected and do not indicate a problem.

**Comment by psankar** [comment]
Even if I add the `-g` parameter, some more of these INFO messages get printed and nothing else happens. In other PDFs, usually I get the table data printed in the console. In this set of PDFs, the table data is not printed in the console.

**Comment by jeremybmerrill** [comment]
Can you send me the PDF, or attach it to this issue?

**Comment by psankar** [comment]
I need to scrub and remove some sensitive data out of the PDF and fill with some dummy data. I do not have the necessary software licenses handy for that. I will upload in another 4-5 days. Thanks. Sorry for the delay.

**Comment by jazzido** [comment]
Hi @psankar,

I'm curious why you closed this issue. Did you solve your problem?

**Comment by psankar** [comment]
I no longer have access to this data and that is why I closed this issue. Sorry for not being able to help more.
