### ISSUE TITLE
Extend --spreadsheet to handle invisible lines

### ISSUE THREAD

**Issue by malaterre** [tabulapdf/tabula-java#123]
I would be nice to support this kind of tables:

```
$ wget https://static.healthcare.siemens.com/siemens_hwem-hwem_ssxa_websites-context-root/wcm/idc/groups/public/@global/@services/documents/download/mdaw/mtiz/~edisp/x500_1_0_conformance_statement-00074148.pdf
$ java -jar $TABULA --spreadsheet  -p 26 x500_1_0_conformance_statement-00074148.pdf
```

Since this is a multiline table, the option `--spreadsheet` is required here. Without `--spreadsheet` I can extract some stuff, but it is then difficult to join cell text by hand. It would be nice if `--spreadsheet` would not return an empty output.

**Comment by criztovyl** [comment]
Not sure if I copied the link wrong (mobile here), but I get a HTTP 410 Gone?

**Comment by malaterre** [comment]
@criztovyl very odd. I've double checked and it works clicking on the [link directly](https://static.healthcare.siemens.com/siemens_hwem-hwem_ssxa_websites-context-root/wcm/idc/groups/public/@global/@services/documents/download/mdaw/mtiz/~edisp/x500_1_0_conformance_statement-00074148.pdf). Anyway you can go to [this page](https://www.healthcare.siemens.com/services/it-standards/dicom-conformance-statements-ultrasound), search for 'X500'.

**Comment by criztovyl** [comment]
Oh, fck you, Siemens.
> „Your Device is not supported."

**Comment by malaterre** [comment]
@criztovyl :) Can you change your User Agent to 'NONE' ?

**Comment by criztovyl** [comment]
My bad! There is a continue anyway link -.-

**Comment by criztovyl** [comment]
410 is because on the DL server that „Your device is not supported”-file is missing.
Let's try shell.

**Comment by criztovyl** [comment]
Finally, shell worked. \o/
You mean that tables like Table 2, 3 o. 4? :)

**Comment by malaterre** [comment]
Technically I want `Table 6 Ultrasound Image and Ultrasound Retired Image IOD Attributes` (page 24-29), `Table 7 Ultrasound MultiFrame and Ultrasound MultiFrame Retired Image
IOD Attributes` (page 30-36), `Table 8 Secondary Capture Image IOD Attributes` (page 37-41) and `Table 9 Comprehensive SR IOD Attributes` (page 41-43).

**Comment by jeremybmerrill** [comment]
Unfortunately, there are no invisible lines in this PDF, just white spaces. The "stream"/no-spreadsheet algorithm is built to use these white spaces; the spreadsheet/"lattice" algorithm needs actual line primitives in the PDF to work. There is, unfortunately, no way I know of to transform white spaces into lines in the general case into lines with sufficient confidence to use the lattice algorithm: even though our eyes can make the distinction easily, the computer can often see white lines when we know there aren't any, e.g. ["rivers"](https://en.wikipedia.org/wiki/River_(typography)). 

So, unfortunately, that PDF lacks lines, so the spreadsheet algorithm will not work on it. The "stream" mode output is the best you're going to get. I know it's a pain to try to combine cells, but we have not been able to come up with a general purpose method for combining them.

I've attached the table we're talking about: 
[ultrasound-26.pdf](https://github.com/tabulapdf/tabula-java/files/614774/ultrasound-26.pdf)
