### ISSUE TITLE
CONVERTING SELECTED PAGES

### ISSUE THREAD

**Issue by sidmohan** [tabulapdf/tabula-java#125]
Hello all, is there any option of converting selected pages of PDF into excel / csv? i mean to say if i want to convert only tables present on page 12 to 20 of the PDF then what option do i have? regards

**Comment by jeremybmerrill** [comment]
please check the readme: https://github.com/tabulapdf/tabula-java/blob/master/README.md

**Comment by sidmohan** [comment]
thanks for the reply, in my table the table headers have some special characters like Degree Celcius represented as ºC but in the output it gets distorted to ÂºC. Similarly there are other special characters, which are not getting converted like ohm symbol , how can these be taken care off? regards

**Comment by jeremybmerrill** [comment]
That's an issue with the encoding that whatever software you're using to open the CSV is using, not a Tabula issue. You should check the options for your spreadsheet software to display non-breaking spaces as spaces, not as Â.

**Comment by sidmohan** [comment]
thanks for the reply, i am using Microsoft excel to open the CSV,  any hint on how to do this in MS excel?

**Comment by sidmohan** [comment]
Request help on last inquiry

**Comment by sidmohan** [comment]
can Tabula be used to compare 2 tables in side PDFs? i mean say there is a new version of same old PDF and  i want to compare tables in the old and the new versions of PDF rather than pulling out those in CSV format and doing manual comparision

**Comment by sidmohan** [comment]
Request advise on -can Tabula be used to compare 2 tables in side PDFs? i mean say there is a new version of same old PDF and i want to compare tables in the old and the new versions of PDF rather than pulling out those in CSV format and doing manual comparision

**Comment by criztovyl** [comment]
I think the feature you request is out of scope of Tabula which is about extracting data.
You will have to search another tool thst compares the data, sry.
Correct me if I'm wrong.

**Comment by sidmohan** [comment]
Thanks i will check for that, i can see that from command line there is option to extract particular pages from tabula. Is there any option in the GUI from where we can select particular pages in a batch to extract data from ?

**Comment by criztovyl** [comment]
Unfortunately I know too less about the GUI to answer that.

**Comment by sidmohan** [comment]
can anyone please let me know how to display non-breaking spaces as spaces, not as Â when opening CSV generated from tabula in MS Excel?

**Comment by criztovyl** [comment]
You need to change the import charset.
In 2010 use:
Data &rarr; External Data &rarr; From Text &rarr; Choose your file &amp; Open &rarr; Change the Charset Dropdown (try UTF 8).

**Comment by sidmohan** [comment]
i have tried this but its not working, any other work around. is it confirmed that the charset is to be UTF 8?
