### ISSUE TITLE
Batch:Unrecognized option

### ISSUE THREAD

**Issue by bglar** [tabulapdf/tabula-java#128]
When running the command line tabula against my batch pdf folder ``java -jar tabula-0.9.1-jar-with-dependencies.jar --batch /dir/to/pdf/document/``, I get ``Error: Unrecognized option: --batch``. 

I also noticed that if you run ``java -jar lib/tabula-0.9.1-jar-with-dependencies.jar --help``, ``-b, --batch`` is not listed as an option. I can see that it is in the [code base](https://github.com/tabulapdf/tabula-java/blob/793525a871c5e0374c6c5c22a2141ae7c7728ab4/src/main/java/technology/tabula/CommandLineApp.java#L282) though. Does anyone know the reason why that option is missing?

**Comment by jazzido** [comment]
Hi @bglar,

The `--batch` option hasn't been released yet. You would need to compile the `jar` yourself from the `master` branch.
