### ISSUE TITLE
Differences in output between Ruby and Java implementations

### ISSUE THREAD

**Issue by gavia** [tabulapdf/tabula-java#13]
I have successfully managed to use the ruby implementation of tabular to export text to CSV using the original/basic algorithm, however I'm having trouble replicating this with the java implementation (using scala). I've managed to get it to output some text, but not all!

The ruby code is:

```ruby
require 'tabula'

pdf_file_path = "in.pdf"
outfilename = "out.csv"

out = open(outfilename, 'w')

options = {
    :detect_ruling_lines => false,
    :extraction_method => "original",
}

area = Tabula::ZoneEntity.new(0, 0, 10000, 10000)

extractor = Tabula::Extraction::ObjectExtractor.new(pdf_file_path,
                                            :all,
                                            options)

extractor.extract.each do |pdf_page|
  out << pdf_page
             .get_area(area)
             .get_table
             .to_csv
  out << "\n\n"
end

out.close
```

As you can see, I'm defining a large area as a catch all for each page, however it's worth noting that when I remove the line ```.get_area(area)``` it still gives the same output.

The scala code is

```scala
import java.lang.StringBuilder
import org.nerdpower.tabula._
import org.apache.pdfbox.pdmodel.PDDocument
import org.nerdpower.tabula.extractors.BasicExtractionAlgorithm
import org.nerdpower.tabula.writers.CSVWriter

object ObjectExtractorTest {
  def main(args: Array[String]) {
    var out_file_path = "out.csv"

    val pdf_document = PDDocument load "in.csv"
    val oe = new ObjectExtractor(pdf_document)
    val pi = oe.extract()
    var i = 0
    while (pi.hasNext) {
      i = i + 1
      println("Page " + i + ":")

      var page = pi.next
      //page = page.getArea(0,0,10000,10000)
      val table = (new BasicExtractionAlgorithm).extract(page).get(0)

      val sb = new StringBuilder
      (new CSVWriter).write(sb, table)

      println(sb.toString)
      println("\n\n")
    }
  }
}
```

This is pretty similar to the ruby code except that this time I'm not choosing a specific area and instead allowing tabula to infer the area. This works for some pages, but most of the pages come back blank.

You'll see that I also have a commented out line that selects an arbitrarily large area. I've found that when I remove the comments from that line, the program crashes:

```java
Exception in thread "main" java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(AbstractList.java:350)
	at java.util.Collections.min(Collections.java:605)
	at org.nerdpower.tabula.Page.getArea(Page.java:52)
	at org.nerdpower.tabula.Page.getArea(Page.java:81)
	at ObjectExtractorTest$.main(main.scala:20)
```

Any ideas what I'm doing wrong?

**Comment by jazzido** [comment]
Hi @gavia, sorry for the delay in getting back.

I'll take a look at the exception you reported. In any case, it you need to operate on the the entire page, there's no need to call `getArea`. 

Also, if you have the chance, I would like to see an example document for the behavior you describe (*"This works for some pages, but most of the pages come back blank."*)

**Comment by gavia** [comment]
It looks like the exception issue I was having was due to my use of `pi.next`. @tmccarthy can explain in more detail as he is the one that figured it out.

**Comment by jazzido** [comment]
OK. Closing this issue, then. Please post a new one if the issue persists. Thanks!
