### ISSUE TITLE
List compatible java versions in readme - not yet compatible with openjdk 9

### ISSUE THREAD

**Issue by jason-neal** [tabulapdf/tabula-java#135]
As discussed in [tabula-py#14]( https://github.com/chezou/tabula-py/issues/14)
` tabula-java` does not yet work with the `openjdk version "9-internal"` on linux64  ubuntu & fedora
```
(eniric) ~/P/C/R/tabula-py ❯❯❯ java -version                                  ⏎
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```
As such a list of compatible java versions in the readme could be good.

**Comment by jeremybmerrill** [comment]
This issue should be fixed in the (not yet announced, and released earlier
this week) Tabula 0.9.2. (and it's been fixed in master for months).

Can you verify that the newest version works for you?

Jeremy B. Merrill

**Comment by jason-neal** [comment]
Yes I can confirm that the new version does work.
Thanks.

**Comment by jeremybmerrill** [comment]
Glad to hear it.
