### ISSUE TITLE
Upgrade pdfbox dependecy to version 2.1.0?

### ISSUE THREAD

**Issue by chzhong** [tabulapdf/tabula-java#136]
PDFBox had upgraded to 2.1.0. When would tabula migrate to support new version of pdfbox?

**Comment by jeremybmerrill** [comment]
Soon. Check out the https://github.com/tabulapdf/tabula-java/tree/pdfbox2.0 branch. @jazzido and @melisabok will be able to say whether the target is 2.0 or 2.1.

**Comment by melisabok** [comment]
Yes, we are working on the migration to the version 2.0.4 that I see is the latest one, there is no version 2.1 yet.

**Comment by jazzido** [comment]
Closing as duplicate of #52.
