### ISSUE TITLE
Specific page extraction from GUI

### ISSUE THREAD

**Issue by sidmohan** [tabulapdf/tabula-java#137]
Hi All, i can see that from command line there is option to extract particular pages from tabula. Is there any option in the GUI from where we can select particular pages in a batch to extract data from ?

**Comment by jazzido** [comment]
Hi @sidmohan,

The GUI allows you to extract areas from specific pages, and to 'repeat' a selection. It can also export the equivalent `tabula-java` command.

**Comment by sidmohan** [comment]
thanks what i meant to ask is that is there any option in GUI to enter page nos. directly rather than manual selection . Like in command line we have option to give the page nos.

**Comment by jazzido** [comment]
Not at the moment, we'll definitely keep that in mind.

**Comment by sidmohan** [comment]
thanks can Tabula be used to compare 2 tables in side PDFs? i mean say there is a new version of same old PDF and i want to compare tables in the old and the new versions of PDF rather than pulling out those in CSV format and doing manual comparision

**Comment by jazzido** [comment]
It does not support comparisons of two different documents.
