### ISSUE TITLE
"Stencil masks are not implemented"

### ISSUE THREAD

**Issue by indypacer** [tabulapdf/tabula-java#139]
Hi all,

Fairly new to Tabula. I'm using tabula-java-0.9.2 on Linux. When I call it from the command line or a Python script, there's an error that says "WARNING: Stencil masks are not implemented, background may be incorrect." I can't find any references to what this means or how to resolve it. Can anyone lend some insight?

Thanks!

**Comment by jeremybmerrill** [comment]
I'm pretty sure that's not an actual error, but just a warning (uncaught, which is our mistake) from a library underlying Tabula. Is Tabula working correctly for you? If it's not, I suspect you either have a really weird PDF or the error is unrelated to that message.

**Comment by indypacer** [comment]
Thanks Jeremy. I came back to edit and mention that it doesn't seem to actually impact the output of the file. Appreciate the quick reply!
