### ISSUE TITLE
Coordinates Tabula Java

### ISSUE THREAD

**Issue by paulohpcardoso** [tabulapdf/tabula-java#14]
Hello, I am new to using the Tabula and would like help to find the coordinates on the site in the Java version. Thank you.

**Comment by jazzido** [comment]
Hello @paulohpcardoso,

I'm not sure what your question is, but if you are looking for documentation for `tabula-java` there isn't much at the moment. You can find some usage tips on the [`test` code](https://github.com/tabulapdf/tabula-java/tree/master/src/test/java/org/nerdpower/tabula)
