### ISSUE TITLE
cli: -l and -t parameters have no effect

### ISSUE THREAD

**Issue by fleger** [tabulapdf/tabula-java#141]
Hi,

Using tabula 0.9.2, the -l and -t parameters are not working as expected.
Deprecated parameters -r and -n are working fine.

**Comment by criztovyl** [comment]
[CommandLineApp#whichExtractionMethod](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L226) seems to use `-r` and `-n`.

**Comment by criztovyl** [comment]
Fixed with #142.

**Comment by fleger** [comment]
Thanks.

**Comment by criztovyl** [comment]
@fleger You may close this issue, if the problem is fixed. :)
