### ISSUE TITLE
Latest release 0.9.2 exposes wrong version number

### ISSUE THREAD

**Issue by Stephan972** [tabulapdf/tabula-java#145]
I downloaded tabula-0.9.2 from this link: https://github.com/tabulapdf/tabula-java/releases/download/0.9.2/tabula-0.9.2-jar-with-dependencies.jar

When I run the jar:

     java -jar tabula-0.9.2-jar-with-dependencies.jar -v

Here is the response:

    tabula 0.9.1 (c) 2012-2016 Manuel Aristarán

The version printed in the response isn't the expected one.

**Comment by jeremybmerrill** [comment]
Ha, oops. that'll be fixed on the next build, I suppose. Thank you for noticing!
