### ISSUE TITLE
Error: Need one filename.

### ISSUE THREAD

**Issue by OrsuSuni** [tabulapdf/tabula-java#148]
Where should i exactly provide the input pdf file path? Can you please update me?
I have download the zip file and imported it to the eclipse. After that i have executed Command Line App. and it is showing error as 
Error: Need one filename
Try --help for help

I am not getting where should i give the pdf file path to parse and save it in the excel file. 

![error](https://cloud.githubusercontent.com/assets/26080134/23899974/67d66cd6-08dd-11e7-9904-46213eb593c7.png)

**Comment by jeremybmerrill** [comment]
@OrsuSuni: tabula-java is meant to be executed on the command line, where you'd run something like `java -jar tabula-0.9.2-jar-with-dependencies.jar path/to/my.pdf`... 

I imagine you can do something similar in Eclipse.

**Comment by jazzido** [comment]
Yes, you can. See here: http://stackoverflow.com/questions/19646719/eclipse-command-line-arguments

**Comment by chaitusg** [comment]
@OrsuSuni  did you finished executing CommandLineApp successfully?
