### ISSUE TITLE
DPDF CONVERSION

### ISSUE THREAD

**Issue by sidmohan** [tabulapdf/tabula-java#149]
CAN ANYONE PLEASE HELP ME TO CONVERT THE PDF PAGE 9 TABLES INTO EXCEL FORMAT

http://www.mouser.com/ds/2/268/mic2940-778896.pdf

**Comment by jazzido** [comment]
If you mean this table, Tabula can't process it. It's an image, and Tabula only can process text.

![image](https://cloud.githubusercontent.com/assets/27584/23914805/7595c1b6-08bd-11e7-86a9-e7c134e343db.png)

**Comment by sidmohan** [comment]
yes this table , can you please advise on how to extract similar tables ? any other open source tool for this ?
