### ISSUE TITLE
RTL bug: numbers are reversed in RTL PDFs when they shouldn't be

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula-java#154]
[الكتاب الاحصائي 2013-2014.pdf](https://github.com/tabulapdf/tabula-java/files/890413/2013-2014.pdf)

"16" comes out as "61" and -- oddly -- "2014" comes out as "0214" which means I'm dealing with "reversing" aka "logically ordering" text characters incorrectly.

As reported on Twitter by @ddiMENA: https://twitter.com/ddiMENA/status/848757808367620097

**Comment by abedkhooli** [comment]
Here's a screenshot comparing source and preview (concerning letters). Test done on Win 7 and Win 10. Most likely issue with pdf production from source (tested another file distilled from Acrobat and worked OK).
![tabula-ar](https://cloud.githubusercontent.com/assets/11407254/24641666/1b37b0be-190a-11e7-89c6-9ce61ee3aa5f.png)

**Comment by jeremybmerrill** [comment]
@abedkhooli Thanks! I hope to find time soon to fix this.

**Comment by jeremybmerrill** [comment]
hahaha "Famasteen." 

I don't think we're going to be able to fix this problem, It comes out the same way, lam to mim, `‫فمسطين‬`, when I copy out of Evince, so it means whatever generated the PDF did a bad job with Arabic, by encoding the glyph for lam under the character mim. 

I think the problem with the numbers is the same problem. In many cases, the character `2` is extracted for the glyph `0` and vice versa. The glyph "6" is mapped to the character "1".

Either this PDF is totally screwed up or this requires the feature PDFBox apparently lacks (and Evince lacks too) `INFO: OpenType Layout tables used in font ABCDEE+Simplified Arabic are not implemented in PDFBox and will be ignored`
