### ISSUE TITLE
Character in cell boundary not read

### ISSUE THREAD

**Issue by paponcc** [tabulapdf/tabula-java#157]
If a character in a text in a table cell is close to the boundary then it is nor read by Cell.getText(). Kindly let me know if any way we can read entire text in a cell with tabula java api.

In attached pic text 'No SS Number' in the cell is read as 'o SS Number'.

![table](https://cloud.githubusercontent.com/assets/27289709/24948704/d055d9d8-1f88-11e7-9486-89c6d09a5cbd.jpg)

**Comment by jeremybmerrill** [comment]
Hi @paponcc, the problem is that the characters overlap the ruling line, which is confusing Tabula. You could try "Stream" mode, but that might cause other problems for you.

**Comment by zhpjy** [comment]
Modify the method for determining whether text is within a bounding box.
Modify this file: RectangleSpatialIndex.java.
```
         for (T ir: intersection) {
-            if (r.contains(ir)) {
+            if (contains(r,ir)) {
                 rv.add(ir);
             }
         }

         Utils.sort(rv, Rectangle.ILL_DEFINED_ORDER);
         return rv;
     }
-    
+
+    private boolean contains(Rectangle r, T ir){
+        double w = ir.getWidth();
+        double h = ir.getHeight();
+        double x = ir.getX();
+        double y = ir.getY();
+
+        if (r.isEmpty() || w <= 0 || h <= 0) {
+            return false;
+        }
+        double x0 = r.getX();
+        double y0 = r.getY();
+        return (
+//                x >= x0 &&
+//                y >= y0 &&
+                (x + w) <= x0 + r.getWidth() &&
+                (y + h) <= y0 + r.getHeight());
+    }
+
```
