### ISSUE TITLE
How to just extract tables from pdf instead of grabbing everything?

### ISSUE THREAD

**Issue by Reapor-Yurnero** [tabulapdf/tabula-java#159]
I'm using tabula-java by
`java -jar ./target/tabula-0.9.2-jar-with-dependencies.jar -o ./tmp/1.csv ./input/directory.pdf`
But the output csv contains everything of this pdf roll by roll, instead of just outputting tables.

What's wrong and what should I do?

Thanks!

**Comment by jazzido** [comment]
Hi @Reapor-Yurnero,

Either `-a`/`--area` or `-g`/`--guess` will help you. https://github.com/tabulapdf/tabula-java#usage-examples

**Comment by Reapor-Yurnero** [comment]
@jazzido Hi, thanks for your reply. But after I add -g, it shows
`Apr 15, 2017 12:25:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont drawString
WARNING: Changing font on <月> from <XXTIRD+FangSong> to the default font`

This did not affect the output csv result but it repeated for every word in this document and made the whole process long and messy. Even if I add '-i', these warnings still appear. How could I deal with it?

Thanks!
