### ISSUE TITLE
New version 1.0.0... password not working

### ISSUE THREAD

**Issue by sharmasourabh** [tabulapdf/tabula-java#167]
jdk8/bin/java -jar tabula-1.0.0-jar-with-dependencies.jar --password XXX A.PDF
Error: Cannot decrypt PDF, the password is incorrect

Also, java -cp tabula-1.0.0-jar-with-dependencies.jar technology.tabula.debug.Debug does not support --password.

Am I missing something?

**Comment by jazzido** [comment]
thanks @sharmasourabh,

That was an oversight on my part. PDFBox API changed substantially and I forgot to port over the password handling logic.

Can you test the attached build? (change the file extension from `zip` to `jar`) 

[tabula-1.0.1-SNAPSHOT-jar-with-dependencies.zip](https://github.com/tabulapdf/tabula-java/files/1167128/tabula-1.0.1-SNAPSHOT-jar-with-dependencies.zip)

**Comment by sharmasourabh** [comment]
Thanks @jazzido for quick fix. It is working now :+1:

**Comment by sharmasourabh** [comment]
Hi @jazzido, 
Forgot to check one thing - any idea when new version would be available on maven repo?
