### ISSUE TITLE
Error if a row has an "extra" column

### ISSUE THREAD

**Issue by psychemedia** [tabulapdf/tabula-java#179]
[POSTED TO WRONG REPO - MEANT TO BE IN `chezou/tabula-py`]

I'm getting a `pandas` parse error using the file:

[btcc-example.pdf](https://github.com/tabulapdf/tabula-java/files/1229832/btcc-example.pdf)

presumably because one row has more cells than the the ones preceding it.
```
----> 1 df = tabula.read_pdf("data/2017/btcc-round1.pdf", pages=62, stream=True,lattice=False)

/usr/local/lib/python3.6/site-packages/tabula/wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
     95         pandas_options['encoding'] = pandas_options.get('encoding', encoding)
     96 
---> 97         return pd.read_csv(io.BytesIO(output), **pandas_options)
     98 
     99

...
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read (pandas/_libs/parsers.c:10862)()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory (pandas/_libs/parsers.c:11138)()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows (pandas/_libs/parsers.c:11884)()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows (pandas/_libs/parsers.c:11755)()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error (pandas/_libs/parsers.c:28765)()

ParserError: Error tokenizing data. C error: Expected 6 fields in line 8, saw 7
```

As a stop gap, should the the `pandas` dataframe be sized to the maximum number of items in a row (the max length of the row lists in the JSON representation), padding short rows with nulls, and then let the user fudge the result? Alternatively, set the columns from the column width and try to populate any long row(s) correctly?

The yellow highlight area is also giving some issues - e.g. with the extraction only extracting the highlighted areas under some circumstances?

**Comment by gandhis1** [comment]
You should report this in the tabula python repo.

**Comment by psychemedia** [comment]
@gandhis1 Yes, sorry about that - wrong tab:-(
