### ISSUE TITLE
Some tables' numbers are extracted wrong from pdf

### ISSUE THREAD

**Issue by oryahud** [tabulapdf/tabula-java#180]
# Summary of your issue
Some tables' numbers are extracted wrong from pdf
# Environment
- [ ] `java -version`: 1.8.0_144
- [ ] `tabula-java version`: 1.01
- [ ] OS and it's version: Windows 10
- [ ] Your PDF URL:
[problem.pdf](https://github.com/tabulapdf/tabula-java/files/1232779/problem.pdf)

# Steps to reproduce:
1. Convert "problem.pdf" file into csv file.
2. Some numbers are wrong.
e.g: Line 12 : 3,797 -> 3,777, 5,317 -> 5,337 and there are some more...

## Example command:
java -jar tabula-1.0.1-jar-with-dependencies.jar problem.pdf -o problem.csv

## Other info:
Also reproduce on:
**tabula-py v1.0.0 (python --version`: 3.6.2) with code:**
 df = read_pdf('problem.pdf')
**tabula v1.1.1**

**Comment by jeremybmerrill** [comment]
This is pretty bad; silently changing numbers is something we really really want to avoid.

Is that the exact PDF (unedited)? In particular, I wouldn't be surprised if the code that deals with RTL text, like Hebrew, would be capable causing this.

(Both the web GUI and the Python bindings are downstream of this repo. If there's a problem, it's here, not in those repos.)

**Comment by jeremybmerrill** [comment]
@oryahud I see the same error you're seeing, but it's not just in Tabula. If I open the PDF in Chrome or Evince, the same problem manifests. Unfortunately, there's nothing I can do to help -- the PDF you have is broken.

**Comment by oryahud** [comment]
This PDF indeed contains Hebrew text but when I open it in Chrome or Evince the problem does not manifests.

**Comment by jeremybmerrill** [comment]
@oryahud Thanks for the screenshot. I'm a little confused -- I don't see any Hebrew in there, just "a" and "s" and numbers... (אני קורה קצת עברית. ) 

Can you try selecting and copy pasting the number that says "5317"? When you paste it, is it "5317" or 5337"?

**Comment by oryahud** [comment]
Thanks for your quick response. 
The PDF contained Hebrew but I change it to English due to confidential issues, but be sure in the original PDF I encountered the same issue.
You are more then right when I paste it, it become "5337".
Any suggestions ? 
Thanks !

**Comment by jeremybmerrill** [comment]
Unfortunately, I don't have a lot of suggestions; since the problem exists in lots of PDF readers, the problem is in the PDF itself. Sometimes tools that let you print to PDF can fix problems like this, by re-rendering the PDF; you can try opening the PDF in a PDF reader, then, "printing" it to a PDF to see if that fixes the problem. It could be a problem with the embedded fonts (which generated some warnings when I opened the PDF, but that could be because I don't have common Hebrew fonts) too.

**Comment by oryahud** [comment]
I will try it.
Thanks again for your amazing help !
