### ISSUE TITLE
Multiple areas?

### ISSUE THREAD

**Issue by xdsv** [tabulapdf/tabula-java#181]
I want to extract multiple areas that exist on different pages like:
java -jar tabula-1.0.1-jar-with-dependencies.jar -p 1 -a 340,42,459,572 -p 2 -a 530,20,606,234 test.pdf

Is this possible?

**Comment by jeremybmerrill** [comment]
You can duplicate the command once per area, e.g. 
`java -jar tabula-1.0.1-jar-with-dependencies.jar -p 1 -a 340,42,459,572 test.pdf`
`java -jar tabula-1.0.1-jar-with-dependencies.jar -p 2 -a 530,20,606,234 test.pdf`

**Comment by xdsv** [comment]
This takes double the time because there's the overhead of the invocation. 
Are you sure there's no other way?

**Comment by jeremybmerrill** [comment]
There are certainly a lot of other ways! You could write your own script, in Java, a JVM language like Scala,  Python, Ruby or R; those libraries, I think, only incur the startup cost once. 

Another option would be to use the `drip` utility, as discussed in #75 and #82.
