### ISSUE TITLE
Problem extracting full table when part of table is highlighted

### ISSUE THREAD

**Issue by psychemedia** [tabulapdf/tabula-java#182]
Trying to extract tables from page 62 of the PDF http://www.tsl-timing.com/file/?f=TOCA/2017/171303trg.pdf , in which some elements of the table are highlighted:

![image](https://user-images.githubusercontent.com/82988/29965418-5eac90a0-8f05-11e7-943e-2479369d4cde.png)

only the yellow highlighted rows are extracted?

**Comment by jeremybmerrill** [comment]
What's the exact command you're using? I suspect you'll need to specify that you want "stream" mode extraction, not "lattice" (and if you don't pick one, Tabula will guess and, in this case, it probably incorrectly guesses "lattice" mode -- which would be expected to pick up only the text inside rectangles)

**Comment by psychemedia** [comment]
@jeremybmerrill Ah... ok... stream works... So I think my error is with tabula-py ...
