### ISSUE TITLE
Repeating headers

### ISSUE THREAD

**Issue by pranali3215** [tabulapdf/tabula-java#186]
I have the same table continuing on multiple pages and on each page the header is written again.
This makes sense in a pdf format, but not in a csv.

Is there a way so that it ignores the headers and only converts the table?
For example, convert_without_header=True

As far as I know, we can extract ignoring repeating header with extracting each page and dropping header, but it should be inefficient. Is there an efficient extraction available?

**Comment by iWhacko** [comment]
instead of a "convert_without_header", I find an "ignoreRowNumbers=[1]" more robust. As it would work the same as specifying pages to extract.

**Comment by jazzido** [comment]
Thanks for the suggestion @pranali3215. We don't have any plans to implement post-processing operations in Tabula; building a robust extraction method is already quite challenging.

However, it would be quite easy to perform that with a simple _filter_ in your favorite spreadsheet application.
