### ISSUE TITLE
Batch processing on windows?

### ISSUE THREAD

**Issue by wolfkidsounds** [tabulapdf/tabula-java#190]
Hey.

I'm absolutely new with java. I have little experience with the cmd module in windows, but not that much.

My Issue: I need to batch convert some pdf files. 
I used the following code to give me the results I wanted:
`cd "C:\TABULA\"
for %i in (C:/Tabula/data/*.pdf) do java -jar ./tabula.jar -n -p 2 -a 31.951,24.792,564.545,293.226 -b (C:/TABULA/data/pdf/) -o (C:/TABULA/data/%i~ni.csv) (C:/TABULA/data/%i)
`
This gave me the error message:
`Error: Filename specified with batch"
Try --help for help`

I looked into the help file and saw that I did not to something wrong here?
Tabula found my pdf files and also did the naming in cmd correctly but I always get this "naming error".

Also I have some very complex pdf which require multiple "areas" - how can I set this up? (I used the script export method to get the area size).

UPDATE: I used this code, which resultet in no error but also in no output:
`java -jar ./tabula.jar -a 31.951,24.792,564.545,293.226 -b ./data/pdf/ -n -o (./data/csv/*.csv) -p 2 -t`

UPDATE2: Using this code I got the same error as above:
`java -jar ./tabula.jar -a 31.951,24.792,564.545,293.226 -b ./data/pdf/*.pdf -n -o (./data/csv/*.csv) -p 2 -t`

UPDATE3: This code shows the correct paths again, but still gives the Filename error - what am I doing wrong?
`for %i in (*.pdf) do java -jar ./tabula.jar -a 31.951,24.792,564.545,293.226 -b ./data/pdf -n -o ./data/csv/%~ni.csv ./data/pdf/%i -p 2 -t`
![console output](https://user-images.githubusercontent.com/32850639/31631494-1f51f28c-b2ba-11e7-9fdb-5d31ed9e69d3.JPG)

**Comment by wolfkidsounds** [comment]
Hey I still can't really solve the problem. I would really be happy if someone can help me out with this.

Thanks so far that tabula even exists! <3

**Comment by jazzido** [comment]
Hi @wolfkidsounds,

I'm not familiar with the Windows command line interface, but I think that you're giving Tabula an input filename (`./data/pdf/%i`). The point of batch mode is specifying a directory that contains a PDF, instead of a single file.

In other words: if you're using the `-b` option, *don't* give tabula a filename as an argument.

**Comment by arevalom** [comment]
Hello @jazzido im trying to run but give a error i have no idea where is the problem, can you check please: `java -jar tabula.jar -p all -a 113.603,199.283,187.808,255.128 -p 1 "$1" -a 114.368,258.188,187.043,318.623 -p 1 "$1" -a 112.838,321.683,186.278,381.353 -p 1 "$1" -a 115.133,384.413,184.748,471.623 -p 1 "$1" -a 193.163,26.393,250.538,306.383 -p 1 "$1" -a 190.103,307.913,258.953,597.083 -p 1 "$1" -a 264.308,25.628,403.538,301.028 -p 1 "$1" -a 268.898,303.323,411.188,597.848 -p 1 "$1" -a 36.338,24.098,186.278,302.558 -p 2 "$1" -a 35.573,307.148,195.458,592.493 -p 2 "$1" -a 201.578,24.863,299.498,305.618 -p 2 "$1" -a 318.623,25.628,359.168,302.558 -p 2 "$1" -a 441.023,24.863,492.278,305.618 -p 2 "$1" -a 441.788,307.913,492.278,584.078 -p 2 "$1" -b C:\Tabular\RealistReportIn`

Best Regards!

**Comment by arevalom** [comment]
I try to use this and give me a error: `for %i in (c:/Tabular/RealistReportIn/*.pdf) do java -jar tabula.jar -p all -a 113.603,199.283,187.808,255.128 -p 1 "$1" -a 114.368,258.188,187.043,318.623 -p 1 "$1" -a 112.838,321.683,186.278,381.353 -p 1 "$1" -a 115.133,384.413,184.748,471.623 -p 1 "$1" -a 193.163,26.393,250.538,306.383 -p 1 "$1" -a 190.103,307.913,258.953,597.083 -p 1 "$1" -a 264.308,25.628,403.538,301.028 -p 1 "$1" -a 268.898,303.323,411.188,597.848 -p 1 "$1" -a 36.338,24.098,186.278,302.558 -p 2 "$1" -a 35.573,307.148,195.458,592.493 -p 2 "$1" -a 201.578,24.863,299.498,305.618 -p 2 "$1" -a 318.623,25.628,359.168,302.558 -p 2 "$1" -a 441.023,24.863,492.278,305.618 -p 2 "$1" -a 441.788,307.913,492.278,584.078 -p 2 "$1" -o c:/Tabular/RealistReportOut/%~.csv c:/Tabular/RealistReportOut/%i`

**Comment by aralom** [comment]
I try to use this: `for %i in (c:/Tabular/RealistReportIn/*.pdf) do java -jar tabula.jar -p all -a 113.603,199.283,187.808,255.128 -p 1 "$1" -a 114.368,258.188,187.043,318.623 -p 1 "$1" -a 112.838,321.683,186.278,381.353 -p 1 "$1" -a 115.133,384.413,184.748,471.623 -p 1 "$1" -a 193.163,26.393,250.538,306.383 -p 1 "$1" -a 190.103,307.913,258.953,597.083 -p 1 "$1" -a 264.308,25.628,403.538,301.028 -p 1 "$1" -a 268.898,303.323,411.188,597.848 -p 1 "$1" -a 36.338,24.098,186.278,302.558 -p 2 "$1" -a 35.573,307.148,195.458,592.493 -p 2 "$1" -a 201.578,24.863,299.498,305.618 -p 2 "$1" -a 318.623,25.628,359.168,302.558 -p 2 "$1" -a 441.023,24.863,492.278,305.618 -p 2 "$1" -a 441.788,307.913,492.278,584.078 -p 2 "$1" -o c:/Tabular/RealistReportOut/%~.csv c:/Tabular/RealistReportOut/%i`

**Comment by aralom** [comment]
Hello, i just try with this code and give the same error:
`for %i in (c:/Tabular/RealistReportIn/*.pdf) do java -jar tabula.jar -a 113.603,199.283,187.808,255.128 -p 1 "$1" -a 114.368,258.188,187.043,318.623 -p 1 "$1" -a 112.838,321.683,186.278,381.353 -p 1 "$1" -a 115.133,384.413,184.748,471.623 -p 1 "$1" -a 193.163,26.393,250.538,306.383 -p 1 "$1" -a 190.103,307.913,258.953,597.083 -p 1 "$1" -a 264.308,25.628,403.538,301.028 -p 1 "$1" -a 268.898,303.323,411.188,597.848 -p 1 "$1" -a 36.338,24.098,186.278,302.558 -p 2 "$1" -a 35.573,307.148,195.458,592.493 -p 2 "$1" -a 201.578,24.863,299.498,305.618 -p 2 "$1" -a 318.623,25.628,359.168,302.558 -p 2 "$1" -a 441.023,24.863,492.278,305.618 -p 2 "$1" -a 441.788,307.913,492.278,584.078 -p 2 "$1" -b /c:/Tabular/RealistReportIn/ -n -o ./c:/Tabular/RealistReportOut/%~ni.csv ./RealistReportIn/`

**Comment by aralom** [comment]
> 
> 
> Hey I still can't really solve the problem. I would really be happy if someone can help me out with this.
> 
> Thanks so far that tabula even exists! <3

Hello @wolfkidsounds how did you solve the problem?

Regadrs!
