### ISSUE TITLE
Could I Use tabula-java in php?

### ISSUE THREAD

**Issue by Raf2061** [tabulapdf/tabula-java#192]
Eg using exec(java -jar etc etc?

And If the java interpreter is on another server?

Thank very much

**Comment by criztovyl** [comment]
Tabula shouldn't be the problem here.

Although executing a Java Virtual Machine on a remote server via PHP most certainly will be complicated, but that's not an issue of Tabula.

Anyway, I'm curious, what's your use-case?

**Comment by iWhacko** [comment]
You could use Tabula-Api to make Tabula remotely accessible.

**Comment by habibzeeshan** [comment]
Can any one tell me the proper steps pleas for this question
