### ISSUE TITLE
Arabic Letters are ???

### ISSUE THREAD

**Issue by AliBassam** [tabulapdf/tabula-java#204]
I have a PDF file that contains both Latin characters and Arabic characters. The Latin characters are extracted correctly however the Arabic ones are appearing as question marks. Is there any encoding parameter that can be set?

**Comment by jeremybmerrill** [comment]
Tabula successfully outputs UTF-8 encoded text across many languages and writing systems, whether Chinese/Japanese/Korean, Arabic/Farsi, Hebrew, or Indian languages like Hindi and Marathi.

If Tabula correctly displays the text in the Tabula browser window, but the text looks different when you open it in Microsoft Excel, you have an Excel problem. You'll have to tell Excel specifically to open the CSV with UTF-8 encoding. Here's a guide for Excel 2007 on Windows, you may have to find a different one for your version of Excel: https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0

If Tabula correctly displays the text in the Tabula browser window, please reopen this bug.
