### ISSUE TITLE
Creating jar file with dependencies using the latest version

### ISSUE THREAD

**Issue by Kanz95** [tabulapdf/tabula-java#208]
The latest version of the jar file with dependencies available for command line tool is 1.0.1. Due to that, I am getting  different outputs in Tabula app and the command line, for the same pdf. So, I tried building a jar file with dependencies with the latest version of the code (1.2.0) for the command line tool, but I am not getting any jar-with-dependencies file, even though build is successful.

**Comment by jazzido** [comment]
Hi @Kanz95,

You might want to refer to [Tabula app's build instructions](https://github.com/tabulapdf/tabula#building-a-packaged-application-version). We've just released 1.2.0, which includes the latest version of tabula-java (1.0.1).
