### ISSUE TITLE
Multilines cells not well detected with guess mode

### ISSUE THREAD

**Issue by mrbidon** [tabulapdf/tabula-java#210]
Hello,

I'm trying to use your fantastic piece of software to analyse the table provided in page 1 of this pdf :
[input.pdf](https://github.com/tabulapdf/tabula-java/files/1796918/input.pdf)

I'm using the last version of tabula-java. I compiled it thought git and mvn (as specified in readme.md).

I execute this command line : 
`java -jar target/tabula-1.0.2-SNAPSHOT-jar-with-dependencies.jar -g input.pdf > output.csv`

I've got the following output : [output.txt](https://github.com/tabulapdf/tabula-java/files/1796922/output.txt)

But, I expect this : [output_expected.txt](https://github.com/tabulapdf/tabula-java/files/1796925/output_expected.txt)

Do you think is that possible ?

**Comment by jazzido** [comment]
Hi @mrbidon,

Thanks for your report. Looks like Tabula is having trouble detecting the proper extraction mode for that document. Forcing _lattice_ mode seems to work well for that table:

![image](https://user-images.githubusercontent.com/27584/37208737-35ef3eea-2381-11e8-83cf-784e43cd7883.png)

Try to specify the area of extraction _and_ forcing lattice (`-l`) mode.

**Comment by mrbidon** [comment]
Could you give a simple way (tools) to find the correct area  ?

**Comment by jazzido** [comment]
Tabula itself! Get it here: http://tabula.technology — The _script_ export format contains the area of interest:

![image](https://user-images.githubusercontent.com/27584/37209055-7b552660-2382-11e8-9417-d8ff0ddfa778.png)

**Comment by mrbidon** [comment]
Thanks !

**Comment by mrbidon** [comment]
I tested with tabula itself, and indeed it works out of the box : 
- automatic selection of the table
- Latice selection

So I think that there is something wrong with tabula-java because even with the -l option, I haven't got this result.

ps : tabula is enough for me

**Comment by My3VM** [comment]
Hello there,
I've come across similar scenario to detect the tables followed by MultiLine cells. I've tried the above idea, though it works in major cases, the last row gets omitted in rest of the cases.

Tried to achieve similar workflow by tweaking code to handle both -g -l option which first guesses the rect and then passes the rectangles with SpreadsheetDetection algorithm, but the observation is still the same..last rows get skipped.

Please suggest how could I augment both guess option and lattice way of extraction.
