### ISSUE TITLE
Way to deal with CSV with specific separator (not comma)

### ISSUE THREAD

**Issue by squalou** [tabulapdf/tabula-java#220]
Hi,

I know the 'C' in CSV means comma. 
But, in France, don't ask me why, the 'regular' separator for CSV is a semi-colon.

Any software waits for CSV with semi-colons, even Excel when set in French.

I managed to patch tabula-java : 

```
--- a/src/main/java/technology/tabula/writers/CSVWriter.java
+++ b/src/main/java/technology/tabula/writers/CSVWriter.java

        public CSVWriter() {
-               this(CSVFormat.EXCEL);
+               this(CSVFormat.EXCEL.withDelimiter(';'));
        }

```

this is more a quick and dirty hack than anything else.

An option somewhere would be very convenient.

thanks!

**Comment by jazzido** [comment]
Thanks for the suggestion, @squalou.

We will consider this as an option to the command line app. In the meantime, you can use [`csvfix`](https://neilb.bitbucket.io/csvfix/) in a post-processing step:

`csvfix write_dsv -s ';' input_file.csv`

**Comment by squalou** [comment]
Thanks for the trick !! you saved my day!
