### ISSUE TITLE
Unable to use tabula-java from Maven without JSI 1.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by rikoe** [tabulapdf/tabula-java#224]
Firstly, thanks for the awesome tool. 

I am trying to use the Maven version of tabula-java, but I can't because JSI 1.1.0-SNAPSHOT  is not in the default Maven repo.

My current employer mirrors Maven Central, but not Sonatype Snapshot repository, so I can't get hold of it easily.

Also, we have a policy that we can't publish a release (non-snapshot) JAR if any dependencies are SNAPSHOT ones.

I see that JSI hasn't been updated for years, and is not likely to change. Do you have a strategy to switch to a non-snapshot version in official Maven repo at some point, or to replace it with something similar that is officially released and supported?

**Comment by jazzido** [comment]
Hi @rikoe,

Thanks for dropping by. Yes, replacing `JSI 1.1.0-SNAPSHOT` is something that I've been meaning to do for a while. Unfortunately, I don't have the time to tackle that.

However, we're always open to merging pull requests. Here's an RTree library that looks appropiate to replace JSI in `tabula-java`: https://github.com/conversant/rtree — I think it's good "starter issue" for getting acquainted with `tabula-java`.

Thanks again!

**Comment by jazzido** [comment]
I started this on the `rtree` branch. Still need to fix two failing tests.

**Comment by jazzido** [comment]
@rikoe The `master` branch now uses JTS instead of JSI. I plan to publish a point release to mvn this week.

JTS is published in Maven central, so you should be able to use your employer's mirrors.

Also, don't forget that we accept donations at [OpenCollective](https://opencollective.com/tabulapdf) — Your employer might want to donate ;)
