### ISSUE TITLE
Regression: Spreadsheets not sorted logically

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula-java#23]
see `test_spreadsheets_sorted_by_top_and_right` [link](https://github.com/tabulapdf/tabula-extractor/blob/thinwrapper/test/tests.rb#L677-L701) from tabula-extractor. And note the `sort_by(&:top)` fix in the test bove.

in that test case, the PDF has several tables on top of one another, they come out in an order like 3214 instead of 1234.

**Comment by jazzido** [comment]
This should fix the regression, lemme know.

**Comment by jeremybmerrill** [comment]
yep, verified, thx!
