### ISSUE TITLE
Accessibility of RectangleSpatialIndex

### ISSUE THREAD

**Issue by ejschoen** [tabulapdf/tabula-java#240]
I wonder if it would be possible to make the `RectangleSpatialIndex` class public.  I am working on an alternative `ObjectExtractor` that finds rulings in a different manner, and it wants to make a `Page` the same way that `ObjectExtractor` does.  However, it can't, because RectangleSpatialIndex is private.

Alternatively, if there were a way to invoke a different engine than `ObjectExtractorStreamEngine` from within `ObjectExtractor`, that'd work, too.

**Comment by jazzido** [comment]
Hi @ejschoen,

Those are good suggestions. I can't take care of this at the moment, but I'd be happy to incorporate code that does what you suggest. Feel free to send us a pull request.

Thanks!

**Comment by ejschoen** [comment]
Will do.  As it turns out, it's also possible to feed rulings to the spreadsheet extractor, so it would only be useful for non-spreadsheet extractor tasks.
