### ISSUE TITLE
--debug option not working

### ISSUE THREAD

**Issue by mark-apgar** [tabulapdf/tabula-java#245]
-d and --debug option seem to have no effect.
ex:
java -jar tabula.jar --debug --guess -p 10 myfile.pdf

The above line will find and print the table in the PDF on page 10, but does not:
Print detected table areas instead of processing.

as per the help

**Comment by JianyuanYin** [comment]
i have the same question.

**Comment by cfculhane** [comment]
Bump, this is still happening

**Comment by othyn** [comment]
After playing around, turns out you have to use the debug tool, don't think `--debug` actually does anything.

See: https://github.com/tabulapdf/tabula-java/issues/94

It also doesn't go to STDOUT, it outputs an image of what it sees with what it thinks drawn on. For more info, see the docs:

> It also includes a debugging tool, run `java -cp ./target/tabula-1.0.2-jar-with-dependencies.jar technology.tabula.debug.Debug -h` for the available options.

**Comment by jazzido** [comment]
Indeed. `--debug` is not connected to anything. Also, @othyn is right. As of now, `technology.tabula.debug.Debug` is the best we have.
