### ISSUE TITLE
Feature Request: Repeat to Page XX

### ISSUE THREAD

**Issue by billdenney** [tabulapdf/tabula-java#250]
In the web interface when specifying area repetition, it would be helpful to have the option to "Repeat to Page XX" where you fill in the XX.  I have a document (ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/DVS/natality/UserGuide2017.pdf) where I want to extract the selection from page 10 to 41, but I don't want the text beyond page 41.

**Comment by rosenjcb** [comment]
I actually have a feature like that on the tabula project! It lets you repeat sections to specified pages (e.g. 2-12, 14-16, 20-30).
