### ISSUE TITLE
Is there any possibility to print the output csv in to a file instead of in console while runnning CommandLineApp.java 

### ISSUE THREAD

**Issue by chaitusg** [tabulapdf/tabula-java#252]
only first page in pdf is getting converting in to csv if there are multiple pages in pdf.
Please tell me how to autodetect only tables without headings about data and all!!!

**Comment by jazzido** [comment]
Please paste the command that you're using. 

Also, take a moment to read the help text: https://github.com/tabulapdf/tabula-java#usage-examples — It's all in there.
