### ISSUE TITLE
tabula-java and  tabula auto-detect tables give different results

### ISSUE THREAD

**Issue by laigor** [tabulapdf/tabula-java#260]
tabula-java and  tabula auto-detect tables give different results
For example for file
[example.pdf](https://github.com/tabulapdf/tabula-java/files/2571901/example.pdf)
tabula:
give me this
[
  {
    "page": 1,
    "extraction_method": "stream",
    "selection_id": "X1542028577619",
    "x1": 30.001895919113164,
    "x2": 568.0223525383758,
    "y1": 90.9968955695343,
    "y2": 169.13264653083803,
    "width": 538.0204566192626,
    "height": 78.13575096130371,
    "spec_index": 0
  },
  {
    "page": 1,
    "extraction_method": "stream",
    "selection_id": "B1542028577644",
    "x1": 30.001895919113164,
    "x2": 568.0223525383758,
    "y1": 354.99676186752316,
    "y2": 483.73471345138546,
    "width": 538.0204566192626,
    "height": 128.7379515838623,
    "spec_index": 1
  }
]

tabula-java:
java -jar /usr/local/bin/tabula-1.0.2-jar-with-dependencies.jar -g example.pdf -f JSON
show:
{
    "extraction_method": "stream",
    "top": 0,
    "left": 0,
    "width": 440.54998779296875,
    "height": 167.16000366210938,
...
{
    "extraction_method": "stream",
    "top": 0,
    "left": 0,
    "width": 566.2899780273438,
    "height": 482.2799987792969,
...

**Comment by laigor** [comment]
Top and left in detected tables always zero!!!

**Comment by jeremybmerrill** [comment]
This seems like a real bug.

**Comment by jeremybmerrill** [comment]
This'll be fixed by the above pull request, #264

**Comment by laigor** [comment]
Thank you very much !!! This patch works as expected!!!

**Comment by laigor** [comment]
Please add this changes:
`--- a/tabula-java-78dfa5e5413bcb00aafbc1851c39c326bd676cf2/src/main/java/technology/tabula/json/TableSerializer.java
+++ b/tabula-java-78dfa5e5413bcb00aafbc1851c39c326bd676cf2-m//src/main/java/technology/tabula/json/TableSerializer.java
@@ -30,6 +30,8 @@ public final class TableSerializer implements JsonSerializer<Table> {
                result.addProperty("left",   src.getLeft());
                result.addProperty("width",  src.getWidth());
                result.addProperty("height", src.getHeight());
+               result.addProperty("right",  src.getRight());
+               result.addProperty("bottom", src.getBottom());
 
                JsonArray data;
                result.add("data", data = new JsonArray());`

**Comment by jeremybmerrill** [comment]
can you submit a pull request against my pull request? (GitHub mangled your patch file)

**Comment by laigor** [comment]
https://github.com/tabulapdf/tabula-java/pull/265

**Comment by jeremybmerrill** [comment]
thanks!
