### ISSUE TITLE
Error: Filename specified with batch Tabula-Java usind cmd

### ISSUE THREAD

**Issue by aralom** [tabulapdf/tabula-java#262]
@jazzido @batterseapower @marado @mtigas  Hello, Im trying to use Tabula-Java using Using the command line tabula extractor tool. Using this code:
`for %i in (c:/Tabular/RealistReportIn/*.pdf) do java -jar tabula.jar -a 113.603,199.283,187.808,255.128 -p 1 "$1" -a 114.368,258.188,187.043,318.623 -p 1 "$1" -a 112.838,321.683,186.278,381.353 -p 1 "$1" -a 115.133,384.413,184.748,471.623 -p 1 "$1" -a 193.163,26.393,250.538,306.383 -p 1 "$1" -a 190.103,307.913,258.953,597.083 -p 1 "$1" -a 264.308,25.628,403.538,301.028 -p 1 "$1" -a 268.898,303.323,411.188,597.848 -p 1 "$1" -a 36.338,24.098,186.278,302.558 -p 2 "$1" -a 35.573,307.148,195.458,592.493 -p 2 "$1" -a 201.578,24.863,299.498,305.618 -p 2 "$1" -a 318.623,25.628,359.168,302.558 -p 2 "$1" -a 441.023,24.863,492.278,305.618 -p 2 "$1" -a 441.788,307.913,492.278,584.078 -p 2 "$1" -b ./c:/Tabular/RealistReportIn/ -n -o ./c:/Tabular/RealistReportOut/%~ni.csv ./RealistReportIn/`

Give this error:
Error: Filename specified with batch
Try --help for help
Check this image: [https://i.stack.imgur.com/PPhrh.png](url)
Any Help, will be appreciated.

Regards!

**Comment by jazzido** [comment]
Hi @aralom,

Batch mode does not accept a filename as an argument. You're providing one with the `"$1"` shell argument.

**Comment by aralom** [comment]
Hello @jazzido how this will be fixed, been honest I'm lost. :(
The "$" i take it from my template generated from tabula.

**Comment by jazzido** [comment]
That looks like a bug in the template that we generate. Try removing the `$1`s

**Comment by aralom** [comment]
Already do, like this:
`for %i in (c:/Tabular/RealistReportIn/*.pdf) do java -jar tabula.jar -a 113.603,199.283,187.808,255.128 -p 1 -a 114.368,258.188,187.043,318.623 -p 1 -a 112.838,321.683,186.278,381.353 -p 1 -a 115.133,384.413,184.748,471.623 -p 1 -a 193.163,26.393,250.538,306.383 -p 1 -a 190.103,307.913,258.953,597.083 -p 1 -a 264.308,25.628,403.538,301.028 -p 1 -a 268.898,303.323,411.188,597.848 -p 1 -a 36.338,24.098,186.278,302.558 -p 2 -a 35.573,307.148,195.458,592.493 -p 2 -a 201.578,24.863,299.498,305.618 -p 2 -a 318.623,25.628,359.168,302.558 -p 2 -a 441.023,24.863,492.278,305.618 -p 2 -a 441.788,307.913,492.278,584.078 -p 2 -b ./c:/Tabular/RealistReportIn/ -n -o ./c:/Tabular/RealistReportOut/%~ni.csv ./RealistReportIn/`
And Same message :/

**Comment by jeremybmerrill** [comment]
I think you don't need the for loop if you're using batch mode.

Jeremy B. Merrill
