### ISSUE TITLE
Can not see Form PDF data

### ISSUE THREAD

**Issue by shubhpy** [tabulapdf/tabula-java#273]
Hey,

https://s3.ap-south-1.amazonaws.com/public-sharing-purpose/aoc_gooded_tech.pdf

I have been trying since a long time to read the data inside this PDF with any python library.
Somehow I landed here.

I tried opening this PDF but can not see the data.

History:
So when I open this PDF in Adobe Acrobat Reader, I see security warning of if you trust ... site and it asks to either allow or block. When I allow I can see the data.
But when I open it in Preview(Mac), It doesn't ask anything and shows data.

When I passed this PDF to any Python Library (tabula, PyMuPDF, PyPDF2, pdfminer), I didn't see the data but only fields.

One day, I opened it in Preview(Mac) and exported as PDF.
And Voila It was working and libraries were able to read full data.

Can anyone help me how can I see the full data in python?
Thanks

**Comment by mkl-public** [comment]
*Not a solution, merely an explanation:*
The form structure of the given PDF is broken:
* only very few of the form fields associated with the form field widget annotations on the document pages are referenced from the global document form structure (**AcroForm** dictionary in the **Catalog**);
* the partial names of the form fields (**T** value in the field dictionaries) are invalid, they contain PERIOD characters which is forbidden in partial names:
    > a partial name shall not contain a PERIOD character.

    *(ISO 32000-1 section 12.7.3.2 "Field Names")*

Most PDF processing libraries (in contrast to PDF viewers) will only consider the values of fields referenced from the global document form structure. Invalid field names may furthermore break retrieval of form field values.
