### ISSUE TITLE
fontSize is always 1.0 for all characters, regardless of height or typeface

### ISSUE THREAD

**Issue by billwanjohi** [tabulapdf/tabula-java#277]
We're using tabula-1.0.2 to extract text from regions of various PDFs. We've been using character height as our primary measure for text, but would also like to grab the font size in points for particular elements. Unfortunately the `fontSize` attribute on TextElements for all of the PDFs I've tried are all set to `1.0`. Is there something I'm missing?

**Comment by satyaraj479** [comment]
Yes I too get the same unfortunately.

**Comment by billwanjohi** [comment]
@satyaraj479 we've been relying on [getYScale](https://pdfbox.apache.org/docs/2.0.0/javadocs/org/apache/pdfbox/text/TextPosition.html#getYScale()) for font size in points, and it seems to always work.

**Comment by satyaraj479** [comment]
OK i will try this option @billwanjohi , Have you worked on NurminenDetectionAlgorithm, it doesn't ignore Page headers or footers. Any approach known to you ? I recently raised as an issue as well, 

If you help me it would be a great help ! thanks :)
