### ISSUE TITLE
Merged cells not identified in Lattice Mode (rowspan/colspan)

### ISSUE THREAD

**Issue by bragboy** [tabulapdf/tabula-java#283]
Tabula is doing an amazing job with most of the tables. However, when there are merged cells, tabula is not able to identify them.

**Sample PDF**

![image](https://user-images.githubusercontent.com/1298587/55665639-117d3100-5861-11e9-97bf-577153763360.png)

**Tabula Output in Lattice Mode**

![image](https://user-images.githubusercontent.com/1298587/55665644-307bc300-5861-11e9-97e3-87b9eeff405b.png)

Ideally I would need an output with rowspan and colspan details based on how the cells are merged. Any help/direction would be appreciated. 

[tabula_test.pdf](https://github.com/tabulapdf/tabula-java/files/3050212/tabula_test.pdf)

**Comment by jazzido** [comment]
Hey @bragboy,

Thanks for reporting. Yeah, that's a known limitation of the table extraction methods that we implemented. If selecting tables manually, try leaving the header row out of the selection.

Thanks again!
