### ISSUE TITLE
[Question] why does tabula-java need jai-imageio-core & jai-imageio-jpeg2000

### ISSUE THREAD

**Issue by SKY24** [tabulapdf/tabula-java#288]
The following two dependencies have licensing and distribution issue's . Apache pdfbox restricts their scope to test but tabula-java has them as a dependency in the pom. 

` <dependency>
        <groupId>com.github.jai-imageio</groupId>
        <artifactId>jai-imageio-core</artifactId>
        <version>1.4.0</version>
    </dependency>
    <dependency>
        <groupId>com.github.jai-imageio</groupId>
        <artifactId>jai-imageio-jpeg2000</artifactId>
        <version>1.3.0</version>
    </dependency> `

I'm trying to understand what are dependencies used for in tabula-java. I setup tabula-java locally and remove them from the pom. I see no compile time errors in pom and unit tests pass. 

If so is it fine if I remove them from pom and build locally/ or are these two libraries really needed by tabula-java for its functioning.  

Thanks
Akash

**Comment by SKY24** [comment]
used PDFTextStripper from pdfbox and the text output does not have the decimal point , so I guess tabula is not the culprit here

**Comment by SKY24** [comment]
I believe that these dependencies are required by pdfbox at runtime.  And tabula has added them to the pom file for convenience of the users. 

https://pdfbox.apache.org/2.0/dependencies.html

however, having these dependencies in the pom without restricting the scope makes it difficult to directly integrate tabula into an in house project since the jai libraries have a highly restrictive license.

**Comment by jazzido** [comment]
Hi @SKY24,

As far as I understand (IANAL), both the `jai-imageio-core` and `jai-imageio-jpeg2000` libraries are distributed under the BSD 3-clause license, which is essentially identical to MIT, which we use for Tabula.

I might be entirely wrong, so I'd be happy to continue the discussion.
