### ISSUE TITLE
Command line cell text problem

### ISSUE THREAD

**Issue by cinjon** [tabulapdf/tabula-java#29]
Hi, I ran across an error today with the CLI. You can find a sample page at my public dbx here: https://dl.dropboxusercontent.com/u/881408/6.pdf.

There is one table shown. The web interface does a great job at reading it when Lattice is selected. It gets the output that I'm looking for. However, I need to use the CLI and am doing so with this command - `java -jar ./target/tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar -r -f JSON -g ./6.pdf`.

There, I'm running into a problem where cell (4,1) is being read as `負債比率ュ・フロー対有利子` and cell (5,1) as `レシオレスト・カバレッジ・`. In other words, the CLI is seeing two rows of text in one cell and blending them by having the bottom row replace the top row wherever there is a character.

To be clear, this is *not* happening in the web interface, only in the tabula-java CLI. What is the difference between the two?

**Comment by jazzido** [comment]
Hi @cinjon, thanks for your report.

I've just run that exact command and this is the result I'm getting. I can't read japanese, but the output seem OK to me:

```csv
"",平成22年３月期,平成23年３月期,平成24年３月期,平成25年３月期,平成26年３月期
"自己資本比率",28.1,22.2,20.0,22.1,23.4
"時価ベースの自己資本比率",33.8,25.0,25.5,27.7,34.0
"キャッシュ・フロー対有利子
負債比率",13.0,－,－,5.7,22.3
"インタレスト・カバレッジ・
レシオ",6.4,－,－,20.7,4.8
```

Furthermore, visual analysis of the output of `java -cp target/tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar technology.tabula.debug.Debug -i -l ~/Downloads/6.pdf` seems to indicate that Tabula is recognizing the target table correctly:

![6-1](https://cloud.githubusercontent.com/assets/27584/10398910/985a920c-6e7d-11e5-9ec1-611e1652a1d5.jpg)

Can you elaborate on what you were expecting to get? BTW, the current *stable* version of the web interface does not use `tabula-java`; it uses [`tabula-extractor`](http://github.com/tabulapdf/tabula-extractor).

**Comment by cinjon** [comment]
Hey, thanks for the fast reply Jazzido!

Your checking it caused me to go back and look again and I see that tabula *did* get the right results but my way of checking it caused problems. In particular, I ran into this something like this - http://stackoverflow.com/questions/11018188/python-print-using-carriage-return-and-comma-not-working - where the carriage return is causing problems. I feel like this is a great problem to have though :+1: .

Re tabula-extractor, I got the sense that tabula-java was what extractor was going towards. What are the current differences?

**Comment by jazzido** [comment]
> Re tabula-extractor, I got the sense that tabula-java was what extractor was going towards. What are the current differences?

`tabula-extractor` is our first attempt at building a library to extract tables out of PDF files. It's written in JRuby. `tabula-java` is a much faster, pure-Java rewrite of `tabula-extractor`, which we plan to use as the main extraction backend for the web-UI tool.
