### ISSUE TITLE
Request release with ASF jbig2-imageio

### ISSUE THREAD

**Issue by SKY24** [tabulapdf/tabula-java#290]
Hi Team

I have request. Would it be possible to do a minor version release with the new jbig2-imageio with Apache license ? We're planning to use tabula for one of our internal projects and jbig2-imageio 2.0 has a high risk license and we would want to avoid that. Since the new  version is now under the ASF umbrella import tabula would be relatively easy.

**Comment by SKY24** [comment]
@jeremybmerrill could you help out with this. On a side note, has tabula gone into maintenance mode  ?

**Comment by jeremybmerrill** [comment]
Could you try doing this change and, if it works, submitting a pull request?

**Comment by SKY24** [comment]
> Could you try doing this change and, if it works, submitting a pull request?

That change is already in master.

**Comment by jeremybmerrill** [comment]
I'm not the one with the signing/distribution keys. I'd recommend linking your app against a custom-built local version of tabula-java; there are instructions in the README for building tabula-java locally.

**Comment by jazzido** [comment]
Hi @SKY24 — I've just released 1.0.3 to Sonatype.
