### ISSUE TITLE
Error in reading pdf file

### ISSUE THREAD

**Issue by xiayufeilucy** [tabulapdf/tabula-java#291]
Hello! 
I got this error when I tried to read a pdf file from my laptop. Can anyone help explain what it means and how I can resolve the issue?
Jun 04, 2019 3:05:52 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO: To get higher rendering speed on JDK8 or later,
Jun 04, 2019 3:05:52 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
Jun 04, 2019 3:05:52 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")

**Comment by SKY24** [comment]
@xiayufeilucy This is not an error. Its just pdfbox telling you a way to get faster rendering on an older jre. 

https://pdfbox.apache.org/2.0/getting-started.html
