### ISSUE TITLE
Malformed JSON?

### ISSUE THREAD

**Issue by cinjon** [tabulapdf/tabula-java#31]
The pdf at this link has multiple tables in it: https://www.dropbox.com/s/shrl08zbkwxzcni/17.pdf?dl=0. Tabula will yield results for it but when using the JSON output, those results seem to be malformed JSON and I suspect it's because it's missing a comma. 

The error is returned at the char between the '''}{''' in the part of the output shown below '''...4.26910400390625,"text":"18,512"}]]}{"extraction_method":"spreadsheet...'''

I haven't gone through the code fastidiously but I think it might be a combination of this line -https://github.com/tabulapdf/tabula-java/blob/6a13b03bb77f826d9516f077f123a14a14167803/src/main/java/technology/tabula/writers/JSONWriter.java#L49 - where the JSONWriter outputs, and this line - https://github.com/tabulapdf/tabula-java/blob/6a13b03bb77f826d9516f077f123a14a14167803/src/main/java/technology/tabula/CommandLineApp.java#L180 - where the writer iterates through all the tables.

**Comment by jazzido** [comment]
That's definitely a bug. Additionally, it's not consistent with the output produced by `tabula-extractor`. Since a page can contain more than one table, the JSON object should be an array of objects.

Thanks!

**Comment by jazzido** [comment]
Hi @cinjon — Our new contributor @melisabok has just fixed this (54c162983e3932aebf6dab805ffd7e4106c0ea32).

**Comment by cinjon** [comment]
Great, thanks all!

**Comment by cinjon** [comment]
Another along these same lines, the JSON Writer for multiple pages (e.g. ```... -p all ...```) produces incorrect JSON that looks like ```[][][{"extraction_method":"spreadsheet", ...```, where each array is a page.
