### ISSUE TITLE
Unnecessary ExtractMethod name shows up with CommandLineApp

### ISSUE THREAD

**Issue by chezou** [tabulapdf/tabula-java#313]
After tabula-java v1.0.3, I unexpectedly face ExtractMethod name, i.e., SPREADSHEET or BASIC before the body of the extracted table. That is annoying to parse from STDOUT since the number of extract method name strings is vary depending on the PDF pages.

It'd be nice if we suppress these extra messages. 

```
➜  tabula-py git:(master) ✗ java -jar tabula/tabula-1.0.2-jar-with-dependencies.jar -r tests/resources/data.pdf
mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear
21.0,6,160.0,110,3.90,2.620,16.46,0,1,4
21.0,6,160.0,110,3.90,2.875,17.02,0,1,4
22.8,4,108.0,93,3.85,2.320,18.61,1,1,4
21.4,6,258.0,110,3.08,3.215,19.44,1,0,3
18.7,8,360.0,175,3.15,3.440,17.02,0,0,3
(...snip...)
➜  tabula-py git:(master) ✗ java -jar tabula/tabula-1.0.3-jar-with-dependencies.jar -r tests/resources/data.pdf
SPREADSHEET
mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear
21.0,6,160.0,110,3.90,2.620,16.46,0,1,4
21.0,6,160.0,110,3.90,2.875,17.02,0,1,4
22.8,4,108.0,93,3.85,2.320,18.61,1,1,4
21.4,6,258.0,110,3.08,3.215,19.44,1,0,3
18.7,8,360.0,175,3.15,3.440,17.02,0,0,3
(...snip...)
```

**Comment by jeremybmerrill** [comment]
I can confirm this but can't figure out why. Any ideas, @jazzido?

It seems to be printed to `System.out` directly, as it still shows up in `stdout` when I specify an output file with `-o`. (That is, with `-o`, the table output is correctly written to the output file, while the extraneous `SPREADSHEET` or `DEBUG` is written to `stdout`.)

Additionally, this is written out to `stdout` even if we specify the extraction method with a CLI flag like `-r` (so it's not a consequence of the heuristic/guesser).

**Comment by jazzido** [comment]
Hey, thanks for noticing. The jar that I uploaded to the github releases was built with a temporary debug message. Just updated it.

**Comment by chezou** [comment]
awesome! thanks for quick response!
