### ISSUE TITLE
Data from table is not extract if it is saved as a Path inside the PDF

### ISSUE THREAD

**Issue by raffam** [tabulapdf/tabula-java#314]
I can extract a table if the data inside it is saved as a "Text" PDF object. But I cannot extract the data if it is saved as a "Path" PDF object. Is there a way to implement this?

Moreover I have many PDF files which I would like to extract in an automatic way. The problem is that, while the shape of the table and its boundaries is similar across them, sometimes the text is saved as a "Text" object, while sometimes it is saved as a "Path" object

**Comment by jazzido** [comment]
Hi Raffale,

If the text was converted to curves (paths), a possible workaround is to
process the document with OCR.

--
Manuel Aristarán
http://jazzido.com
