### ISSUE TITLE
Unable to handle Widows 8.3 style path with Command Line app

### ISSUE THREAD

**Issue by chezou** [tabulapdf/tabula-java#331]
Tabula Command-Line app doesn't accept with [8.3 filename path format](https://en.wikipedia.org/wiki/8.3_filename) for PDF file path and output file path with `--outfile` argument.

This should be resolved in tabula-java side using something like [`Path.GetFullPath`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netframework-4.8). This issue occurs when a user tries to use with `%TEMP%` directory on Windows like [this](https://github.community/t5/GitHub-Actions/TEMP-is-broken-on-Windows/td-p/30432).

**Comment by jazzido** [comment]
Hi @chezou,

Thanks for reporting. Can you provide a minimal reproduction case for this issue?

Thanks!

**Comment by chezou** [comment]
This is the example command what I've encountered on GitHub Actions https://github.com/chezou/tabula-py/runs/320309701

```
java -jar d:\\a\\tabula-py\\tabula-py\\.nox\\tests\\lib\\site-packages\\tabula\\tabula-1.0.3-jar-with-dependencies.jar --pages 1 --stream --guess --format CSV --outfile C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpqq4wnjv3 tests/resources/data.pdf
```

with getting `Error: Cannot create file C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpqq4wnjv3\r\n` as an error message.

The full path of the `outfile` is `C:\\Users\\runneradmin\\AppData\\Local\\Temp\\tmpqq4wnjv3`.  This issue tends to occur with the directory with space or long name. 

If it is not enough easy to reproduce, let me know. I'd love to provide another example.

**Comment by chezou** [comment]
In my local machine, I couldn't reproduce this issue.

```
mkdir "Directory with space"
cd "Directory with space\
cp data.pdf ..\path\to\pdf\
cd ..
java -jar tabula-1.0.3-jar-with-dependencies.jar --outfile  C:\Users\chezo\DIRECT~1\foo.csv  C:\Users\chezo\DIRECT~1\data.pdf
 dir DIRECT~1
 ドライブ C のボリューム ラベルは Windows です
 ボリューム シリアル番号は 30D7-D31C です

 C:\Users\chezo\DIRECT~1 のディレクトリ

2019/11/27  12:38    <DIR>          .
2019/11/27  12:38    <DIR>          ..
2019/11/27  12:35            28,330 data.pdf
2019/11/27  12:38             1,298 foo.csv
               2 個のファイル              29,628 バイト
               2 個のディレクトリ  95,369,564,160 バイトの空き領域
```
