### ISSUE TITLE
Wrap Text / Row Configuration Feature Request

### ISSUE THREAD

**Issue by nacu4** [tabulapdf/tabula-java#333]
New to github and tabula, so I apologize if there's issues with this issue / feature request. I use the python wrapper of tabula, but when I submitted the request there, they told me that tabula python was just a wrapper, so I thought I'd try my luck here. 

**Is your feature request related to a problem? Please describe.**
On the PDF files that I have, the data is not always in a super clear format. There are times in which the text on the PDF is "wrapped" onto a second line. Therefore, when the file is exported to CSV, the data is inconsistent. 

**Describe the solution you'd like**
Within the function convert_into... there should be a sub function called "rows" where the user could configure the start point, end point, and number of rows. 
In the screenshot below and example code in the next section, Tabula would then convert the CSV into 1 consolidate row for every instance where the text shows "Line Item" and "Item No" and ignore everything else. 
In addition, the number of rows indicated would force the conversion to wrap text into the designated number of rows. 

The user would type something like this:
columns = (1,2,3,4,5)
start = ('Line Item%', '', '', '', '')
end = ('Item No%', '%%', '', '', '')
rows = 3 (or 1, depending on if you want the start row and end row included in the count)

**Describe alternatives you've considered**
Another option would be to just say "wrap text" Yes/No where, if the text in a column is at the edge, the next row of data would get wrapped 
Another option would be to specify the dimensions of a "typical" row size and the "maximum" row size, with the option to wrap text in a given way. 
This is similar to #309 where we can't cover multiple rows. 

**Additional context**
![image](https://user-images.githubusercontent.com/22282824/70161197-86af3900-1670-11ea-907c-b03608fe5329.png)

**Comment by jeremybmerrill** [comment]
Hi @nacu4, thanks for raising this. I experimented with a feature like this a few years ago, but found that PDFs, unfortunately, can vary pretty widely. The continuation rows can be wrapped above, below or centered, for instance, and so I didn't find much of a generic way to support what you request.
