### ISSUE TITLE
Test fails in JRE != 6

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula-java#34]
The entire test suite passes in JRE 6, but fails in 7 and 8: https://travis-ci.org/tabulapdf/tabula-java/builds/85259388

The offending test is [`TestBasicExtractor.testExtractColumnsCorrectly3`](https://github.com/tabulapdf/tabula-java/blob/master/src/test/java/technology/tabula/TestBasicExtractor.java#L1843)

Possibly related to our custom sorting algorithm that [is used when JRE > 6](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/Utils.java#L134)

**Comment by jazzido** [comment]
…this begs the question: is it worth to keep supporting Java 6?

**Comment by melisabok** [comment]
I found two things about this:
1. [This test](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/Utils.java#L134) has a wrong expected table extraction, there is an unnecessary space in the [line](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/Utils.java#L143) that is falling. So, when I remove that space the test passes in java 7 but it fails in java 6 :/
2. The difference between both executions is in the method [mergeWords](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/TextElement.java#L79) when resolves the list of TextChunk. In Java 6 gets a list of 51 TextChunk objects and in Java 7 gets a list of 50. I printed the lines where there are the differences:

Java 6
```
Line: technology.tabula.Line[x=51.48,y=168.98,w=498.32996,h=11.980002,bottom=180.959991,right=549.809937,chunks='AARON ', 'REGIONAL PULMONARY & SLEEP', ', JOSHUA, N ', 'MEDICINE ', 'WEST GROVE, PA ', 'SPEAKING FEES ', '$4,700.00', ]
add: technology.tabula.TextChunk[x=51.48,y=172.7,w=22.084003,h=4.54,bottom=177.239990,right=73.564003,text="AARON "]
add: technology.tabula.TextChunk[x=161.16,y=168.98,w=97.0,h=4.540011,bottom=173.520004,right=258.160004,text="REGIONAL PULMONARY & SLEEP"]
add: technology.tabula.TextChunk[x=72.72,y=172.7,w=36.124,h=4.5400105,bottom=177.240005,right=108.844002,text=", JOSHUA, N "]
add: technology.tabula.TextChunk[x=161.16,y=176.42,w=30.033997,h=4.54,bottom=180.959991,right=191.194000,text="MEDICINE "]
add: technology.tabula.TextChunk[x=270.84,y=172.7,w=53.074005,h=4.5400043,bottom=177.240005,right=323.914001,text="WEST GROVE, PA "]
add: technology.tabula.TextChunk[x=380.52,y=172.7,w=48.634033,h=4.54,bottom=177.239990,right=429.154022,text="SPEAKING FEES "]
add: technology.tabula.TextChunk[x=522.96,y=171.9,w=26.849949,h=5.340012,bottom=177.240005,right=549.809998,text="$4,700.00"]
```

Java 7

```
Line: technology.tabula.Line[x=51.48,y=168.98,w=498.32996,h=11.980002,bottom=180.959991,right=549.809937,chunks='AARON, JOSHUA, N ', 'REGIONAL PULMONARY & SLEEP', 'MEDICINE ', 'WEST GROVE, PA ', 'SPEAKING FEES ', '$4,700.00', ]
add: technology.tabula.TextChunk[x=51.48,y=172.7,w=57.364002,h=4.5400105,bottom=177.240005,right=108.844002,text="AARON, JOSHUA, N "]
add: technology.tabula.TextChunk[x=161.16,y=168.98,w=97.0,h=4.540011,bottom=173.520004,right=258.160004,text="REGIONAL PULMONARY & SLEEP"]
add: technology.tabula.TextChunk[x=161.16,y=176.42,w=30.033997,h=4.54,bottom=180.959991,right=191.194000,text="MEDICINE "]
add: technology.tabula.TextChunk[x=270.84,y=172.7,w=53.074005,h=4.5400043,bottom=177.240005,right=323.914001,text="WEST GROVE, PA "]
add: technology.tabula.TextChunk[x=380.52,y=172.7,w=48.634033,h=4.54,bottom=177.239990,right=429.154022,text="SPEAKING FEES "]
add: technology.tabula.TextChunk[x=522.96,y=171.9,w=26.849949,h=5.340012,bottom=177.240005,right=549.809998,text="$4,700.00"]
```

It seems that in Java 6 split the name of the first columns: 'AARON ' and ', JOSHUA, N '. And in Java 7 they are together: 'AARON, JOSHUA, N '.

Something different is happening in the mergeWords method.

**Comment by jazzido** [comment]
Awesome debugging, @melisabok. Thank you so much. Do you think it's worth to keep supporting Java 6? I think it's not even publicly supported by Oracle anymore. My vote is to stop supporting Java 6. @jeremybmerrill @mtigas what do you guys think?

Re: the wrong expectation for the test — What does the extraction return that is not matching what we're expected?

**Comment by jazzido** [comment]
(BTW @melisabok, besides @jeremybmerrill you're one of the few developers that were brave enough to actually go deep inside the table extraction algorithms)

**Comment by jazzido** [comment]
The failing test (under Java 7 and 8) is:
```
testExtractColumnsCorrectly3(technology.tabula.TestBasicExtractor)  Time elapsed: 0.504 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<AARON [, JOSHUA, N]> but was:<AARON [JOSHUA N , ,]>
```

For some reason, the commas are being sorted *after* the letters.

**Comment by melisabok** [comment]
@jazzido I think the problem is Java 6, if you fix the EXPECTED_TABLE_EXTRACTION variable(remove the space between AARON and the comma as the pfd shows), the test fails only in Java 6. Java 7 and 8 works fine.

**Comment by jeremybmerrill** [comment]
I would be fine dropping Java 6 support.

Jeremy B. Merrill

**Comment by melisabok** [comment]
@jazzido It seems to be the quicksort implementation, when I force to use Collections.sort the test pass. I'll check it.

**Comment by jazzido** [comment]
Sorting characters is one of the trickiest parts of Tabula. The [comparison operator for `Rectangle`](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/Rectangle.java#L22) is meant for sorting characters in lexicographic (ie left to right and top to bottom) order. The overlap checks cause the sorting to be non-stable and thus breaks the contracts imposed by `Collections.sort` in Java >= 7.

**Comment by melisabok** [comment]
I see, well Rectangle class deserves a good unit test :)

**Comment by jazzido** [comment]
The debugging tool might be useful for this kind of issues. Run `java -cp ./target/tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar technology.tabula.debug.Debug -h` to see the available options.

**Comment by melisabok** [comment]
I could write a unit test to check what it is failing in the Rectangle comparator. I found that ',' after 'AARON' and the 'R' of ''REGIONAL' don't overlap. Comma has y=175.72 and 'R' has y=169.21 and h=4.31 that is 173.52, so the don't overlap vertically and the comparator says that 'R' < ','. 

```
technology.tabula.TextElement[x=72.72,y=175.72,w=1.67,h=1.52,bottom=177.240005,right=74.389999,text=","]
technology.tabula.TextElement[x=161.16,y=169.21,w=4.33,h=4.31,bottom=173.520004,right=165.490005,text="R"]
``` 

[Here](https://github.com/melisabok/tabula-java/blob/fix/test-rectangle-comparator/src/test/java/technology/tabula/TestRectangle.java#L59) is the unit test that I wrote. I'm not sure about how to resolve this in the comparator, it seems that the second column take the space of two rows.

**Comment by jazzido** [comment]
Thanks, @melisabok.

One possible, but a bit hackish, fix could be to sort the contents of each cell AFTER the table is segmented. This bug does not happen when using the Spreadsheet extraction method (see the output of `java -jar target/tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar -a 106.01,48.09,227.31,551.89 -p 1 -r src/test/resources/technology/tabula/frx_2012_disclosure.pdf`). Such method segments the table into cells using separator lines (`class Ruling` in Tabula) and *then* sorts their contents. We could try doing the same for the Basic method (which only uses characters' positions).

Other than that, I'm open to ideas.

Thanks again!

**Comment by melisabok** [comment]
I did the hack (here)[https://github.com/tabulapdf/tabula-java/compare/master...melisabok:fix/sorting?expand=1], but I couldn't resolve how to remove the spaces before the comma that are added in the (mergeWords)[https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/TextElement.java#L183]. 

BTW I'm running the Spreadsheet extraction method and I think the result isn't correct, right?

```
"AANONSEN, DEBORAH, A",,"STATEN ISLAND, NY",MEALS,$85.00
TOTAL,,,,$85.00
"AARON, CAREN, T",,"RICHMOND, VA",EDUCATIONAL ITEMS,$78.80
"AARON, CAREN, T",,"RICHMOND, VA",MEALS,$392.45
TOTAL,,,,$471.25
"AARON, JOHN",,"CLARKSVILLE, TN",MEALS,$20.39
TOTAL,,,,$20.39
"AARON, JOSHUA, N",,"WEST GROVE, PA",MEALS,$310.33
MEDICINE","WEST GROVE, PA",SPEAKING FEES,"$4,700.00"
TOTAL,,,,"$5,010.33"
"AARON, MAUREEN, M",,"MARTINSVILLE, VA",MEALS,$193.67
TOTAL,,,,$193.67
"AARON, MICHAEL, L",,"WEST ISLIP, NY",MEALS,$19.50
TOTAL,,,,$19.50
``` 

This line is wrong:

```
MEDICINE","WEST GROVE, PA",SPEAKING FEES,"$4,700.00"
```

**Comment by jazzido** [comment]
Awesome. I wouldn't worry too much about that extra space. If the hack improves things, and doesn't cause a regression, I'd say we keep it :). 

> BTW I'm running the Spreadsheet extraction method and I think the result isn't correct, right?

It is actually correct, but displaying the CSV on a terminal will make it look wrong. The reason is that there's a `CR` character (the safest way of preserving newlines in a CSV). This is how that output looks in OpenOffice:

![screen shot 2015-10-18 at 2 47 59 pm](https://github-cloud.s3.amazonaws.com/assets/27584/10565792/8c392048-75a7-11e5-987c-7b24717bd1bb.png)

**Comment by jazzido** [comment]
I went ahead and merged [`melisabok/tabula-java/fix/sorting`](https://github.com/melisabok/tabula-java/tree/fix/sorting) — There are no regressions in other test cases, so it's fine.

Thanks again!
