### ISSUE TITLE
Wrong table boundary extraction

### ISSUE THREAD

**Issue by en-ashay** [tabulapdf/tabula-java#372]
It seems that there are some issues in boundary detection of table in the library.

![image](https://user-images.githubusercontent.com/30903814/90563546-a4eaa400-e1c1-11ea-91a7-c11f32112b50.png)

It is detecting the marked content as table using both code and GUI tool.

**Comment by jazzido** [comment]
Thanks @en-ashay — The table detection algorithm does not aim to detect every possible tabular structure. That would be too ambitious, and potentially impossible.

**Comment by en-ashay** [comment]
Can you link me to the table detection code in the repository?

**Comment by jazzido** [comment]
https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/detectors/NurminenDetectionAlgorithm.java
