### ISSUE TITLE
Is this repos still alive?

### ISSUE THREAD

**Issue by luke4u** [tabulapdf/tabula-java#375]
Hello! 

Noticed the lastest pull request is opened 1 year ago. Is anyone still actively managing this repo?

Thank you! 
Luke

**Comment by jazzido** [comment]
Hi @luke4u,

There is no active development in [`tabula`](https://github.com/tabulapdf/tabula) or [`tabula-java`](https://github.com/tabulapdf/tabula-java) at the moment. We'll consider PRs and do bugfix/maintenance release from time to time.

Cheers,

M
