### ISSUE TITLE
Documentation issue: JAR not found in releases page. 

### ISSUE THREAD

**Issue by VenkatSivaraj** [tabulapdf/tabula-java#380]
The documentation says under Downloads section that the JAR file is available in the Releases page, but only source code is available in zip and tar format.

**Comment by brandonrobertz** [comment]
I ran into the same thing. You're gonna have to either compile 1.0.4 (it's pretty easy) or use the previous version for now: https://github.com/tabulapdf/tabula-java/releases/tag/v1.0.3

**Comment by jazzido** [comment]
Just uploaded the 1.0.4 fat jar to the release: https://github.com/tabulapdf/tabula-java/releases/tag/v1.0.4

**Comment by VenkatSivaraj** [comment]
Thanks @jazzido
