### ISSUE TITLE
specifiy columns only for one area (when multiple areas are extracted)

### ISSUE THREAD

**Issue by ZeeD** [tabulapdf/tabula-java#401]
I have a (bunch of) complex pdf, and I'm using a template to specify 7 different areas to be extracted.
In one of them I want to force the columns.
From what I understand having a quick look it seems that, when multiple areas are used, the same columns pattern is applied.
Is there a way to specify "for this area use those columns" and "for this area find the columns yourself" in the same extraction?

**Comment by jazzido** [comment]
Hey. `tabula` does not support that. the (obvious) workaround would be to split that operation into several calls to the extractor.
