### ISSUE TITLE
ObjectExtractor could implement java.io.Closeable

### ISSUE THREAD

**Issue by seanf** [tabulapdf/tabula-java#408]
It would be nice if `technology.tabula.ObjectExtractor` implemented the standard interface `java.io.Closeable`, since this would work nicely with Java's try-with-resources feature, and similar features in other JVM languages, such as Kotlin's `use` function.

IDEs or other tools sometimes warn when you fail to close a `Closeable` object, so this might help to save a resource leak too.

**Comment by jazzido** [comment]
Good suggestion, @seanf. Thanks.

Just implemented it in a6c322e
