### ISSUE TITLE
Multiple pages JSON output

### ISSUE THREAD

**Issue by cinjon** [tabulapdf/tabula-java#41]
Similar to #31  the JSON Writer for multiple pages (e.g. ```... -p all ...```) produces incorrect JSON that looks like ```[][][{"extraction_method":"spreadsheet", ...```, where each array is a page.

**Comment by melisabok** [comment]
@cinjon do you have an example where I can reproduce the error?

**Comment by cinjon** [comment]
Here's one -
https://www.dropbox.com/s/4nvptahkr1d1w16/2217.2015.09.04.%E5%B9%B3%E6%88%9028%E5%B9%B4-3-10.pdf?dl=0
-
but it should be any pdf with multiple pages.
