### ISSUE TITLE
SIGABRT on Apple M1

### ISSUE THREAD

**Issue by mvanaltvorst** [tabulapdf/tabula-java#435]
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30) 
    [Clang 11.0.1 ] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import tabula
    >>> tabula.read_pdf("/Users/maurits/Informatics/Downloads/test.pdf")
    'pages' argument isn't specified.Will extract only from page 1 by default.
    Error from tabula-java:
    
    
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/io.py", line 322, in read_pdf
        output = _run(java_options, kwargs, path, encoding)
      File "/Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/io.py", line 80, in _run
        result = subprocess.run(
      File "/Users/maurits/miniforge3/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['java', '-Djava.awt.headless=true', '-Dfile.encoding=UTF8', '-jar', '/Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/tabula-1.0.4-jar-with-dependencies.jar', '--guess', '--format', 'JSON', '/Users/maurits/Downloads/test.pdf']' died with <Signals.SIGABRT: 6>.

Error happens on any PDF I try. I suspect this is a problem due to my CPU architecture, but I am not entirely sure unfortunately.

**Comment by jeremybmerrill** [comment]
Interesting! I imagine that any incompatibilities with the M1 chip will be sorted out by upstream software maintainers (i.e. Java) but you might try the downloadable GUI version of Tabula (or the command-line tabula-java, if you're comfrotable on the command line) to see if you get the same errors -- and to rule out a bug with tabula-py, which is not maintained by the core Tabula team.

**Comment by mvanaltvorst** [comment]
You are right Jeremy, installing tabula via `brew install --cask tabula` and using it via the web interface did not cause me any trouble. I wonder if it is possible to use my brew installed tabula instance instead of the bundled one with `tabula-py` to experiment, I suspect `tabula-1.0.4-jar-with-dependencies.jar` might be broken. In any case, given that this problem is not caused by tabula java, I consider this issue closed.
