### ISSUE TITLE
Add a simple API usage example applying SpreadsheetExtractionAlgorithm

### ISSUE THREAD

**Issue by mskopp** [tabulapdf/tabula-java#509]
I have not been able to push against the repo to create a pull request, but here comes some improvement to the README.md:

[diff.txt](https://github.com/tabulapdf/tabula-java/files/10164691/diff.txt)

Full updated README.md file: [README.md](https://github.com/tabulapdf/tabula-java/files/10164708/README.md)

**Comment by jazzido** [comment]
Thanks @mskopp ! If you fork this repo and pushing against that fork instead, you'll be able to create a PR from there.

Otherwise I can apply your changes manually (and credit you in the commit message)

**Comment by mskopp** [comment]
Thank you @jazzido - I created PR #510 and AFAIK _this_ issue should auto-close after merging.

**Comment by jazzido** [comment]
Thanks @mskopp. PR merged to `master`
