### ISSUE TITLE
can not  visit http://dspace.cc.tut.fi/dpub/bitstream/handle/123456789/21520/Nurminen.pdf?sequence=3

### ISSUE THREAD

**Issue by jvhuaxia** [tabulapdf/tabula-java#521]
this website cant visit now
some one have this file copy?
want study
http://dspace.cc.tut.fi/dpub/bitstream/handle/123456789/21520/Nurminen.pdf?sequence=3

**Comment by chezou** [comment]
@jvhuaxia You can find it here https://trepo.tuni.fi/handle/123456789/21520
