### ISSUE TITLE
Outdated maven repo?

### ISSUE THREAD

**Issue by bshewmak** [tabulapdf/tabula-java#63]
Hello, 

This may or may not be an issue. After using **tabula-java** for some time now, it was exciting to see the new _Detection Algorithms_ developed. 

After attempting to move away from a manual build to a _Maven_ build, it seems as though the Maven dependency downloaded doesn't contain the current version of **CommandLineApp.java** as I would have hoped (it is excluding the new detection algorithm implementation, i.e., NurminenDetectionAlgorithm).

I would like to be able to utilize _NurminenDetectionAlgorithm_ by extending **CommandLineApp** class  in my Maven project. Is this (or can this be made) possible?

~ Ben

**Comment by jazzido** [comment]
Hey @bshewmak,

Sorry for the delay. I'm turning in my thesis in 1.5 months so I've been neglecting my side projects :) — I've just released 0.9.0 to OSSRH. Should be available in maven central in a couple hours.

Please let us know if it works.

**Comment by bshewmak** [comment]
Hey @jazzido,

Great news, it appears the Maven repo has updated it's snapshot to the new 0.9.0-SNAPSHOT. Thank you again! By the way, congratulations on your academic accomplishments up to this point. I wish you luck with finishing your thesis. 

~ Ben
