### ISSUE TITLE
Is it possible to read rotated table correctly

### ISSUE THREAD

**Issue by bruce-genhot** [tabulapdf/tabula-java#64]
Hi

Could you help me with reading the rotated table like below ? and how can I check whether a table is rotated ? thank you!

![rotated](https://cloud.githubusercontent.com/assets/11503188/14134165/9792a804-f687-11e5-8c7b-1d1786a5668e.png)

**Comment by jazzido** [comment]
Hi @bruce-genhot,

Currently it is not possible to rotate a PDF page within Tabula. However, you can do so with a PDF viewer application such as Preview (in Mac OS) and re-upload to Tabula.
