### ISSUE TITLE
How to extract title of a table

### ISSUE THREAD

**Issue by bruce-genhot** [tabulapdf/tabula-java#65]
Hi, I'd like to extract the title of a table, is there an existing detector ? for example, I need to extract 'Greehouse gases' from the attached table.

![title](https://cloud.githubusercontent.com/assets/11503188/14135311/5431440a-f68f-11e5-95ae-bed0372aa403.png)

**Comment by jazzido** [comment]
Not currently. Tabula focuses on extracting the table itself.
