### ISSUE TITLE
renamespace into technology.tabula

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula-java#7]
since that's now our canonical home, rather than tabula.nerdpower.org

:)

(FWIW, @jazzido, per our convo ages and ages ago, am converting https://github.com/tabulapdf/tabula-extractor/commit/33abbdbd01498ac925d0444a3bc4f6d8f0647c98 to tabula-java. Am I recalling correctly that that's all you wanted me to implement in tabula-java, or were there issues with spreadsheet extraction too?)

**Comment by filmackay** [comment]
Is this Java port finished/complete to your knowledge compared with the Ruby version?

**Comment by jazzido** [comment]
I've been using it for the last couple months exclusively, so I would say yes. It is much faster and generally more accurate than the original Ruby version.

Here's a compiled version of the latest revision: http://dump.jazzido.com/tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar

**Comment by aosi87** [comment]
Thats some great news, so can do an update already? or is this still exclusive?

Anyway great news =D keep up the good work.

Cheers.

**Comment by jazzido** [comment]
Hey @aosi87,

Nothing is exclusive here, so if the current revision works for you, feel free to use it.

**Comment by gavia** [comment]
So then, @jazzido, are docs coming too?

**Comment by jazzido** [comment]
Hi @gavia,

I work on Tabula in my little free time, so docs haven't been a priority. We will happily accept documentation patches and pull requests, though :)
