### ISSUE TITLE
tabula-0.9.0-jar-with-dependencies.jar missing

### ISSUE THREAD

**Issue by werdlv** [tabulapdf/tabula-java#71]
Usage example references `java -jar ./target/tabula-0.9.0-jar-with-dependencies.jar --help` however it's not found under https://github.com/tabulapdf/tabula-java/releases. There is however JAR for version 0.8.0

**Comment by jeremybmerrill** [comment]
Oops, sorry. I just added one: https://github.com/tabulapdf/tabula-java/releases/tag/tabula-0.9.0

**Comment by werdlv** [comment]
Thanks!
