### ISSUE TITLE
Unable to generate output CSV

### ISSUE THREAD

**Issue by beng06** [tabulapdf/tabula-java#73]
I'm only getting this message below when executing the tabula java using the PDF file in this url (http://www.state.nj.us/comptroller/divisions/medicaid/disqualified/monthly_exclusion_report.pdf). 

The output csv file contains nothing after running the conversion and no errors logs displayed in the console . 

I tried converting this using Acrobat and it was able to convert it to Excel with no issues at all. 

By the way, Tabula is working fine when converting the old version of this pdf (previous month report file from NJ state). Here is the link to the working pdf version (http://www.nj.gov/comptroller/divisions/medicaid/disqualified/monthly_exclusion_report_11_30_2015.pdf)

**Comment by jazzido** [comment]
Did you solve the issue? How?
