### ISSUE TITLE
Specify row height for tables

### ISSUE THREAD

**Issue by mdhoenig** [tabulapdf/tabula-java#74]
I am trying to extract data from a monthly schedule.  It works pretty well, except the grid lines in the spreadsheet are used inconsistently - weekends don't use them so two rows look like one large row:
![2016a-sos_part](https://cloud.githubusercontent.com/assets/8086020/14581785/269b2e34-0391-11e6-9453-75f5bc2ab813.png)

Is there a way I can force _tabula-java_ to use the same height for all rows?  Interestingly enough when using the GUI [Tabula](http://github.com/tabulapdf/tabula) the extraction works fine with the "stream" extraction method, whereas "lattice" gives me the same issues.  But I don't think _tabula-java_ has these options, correct?

**Comment by jazzido** [comment]
Hi @mdhoenig,

To force 'lattice' mode in `tabula-java`, use the `--no-spreadsheet` flag in the command line app.
