### ISSUE TITLE
Using tabula-java (0.8.0) via bash script

### ISSUE THREAD

**Issue by williambusa** [tabulapdf/tabula-java#75]
Congratulations on tabula-java 0.8.0, which I'm using very successfully in an OS X 10.8.5 bash script to extract data from thousands of very complex PDFs. The output is proving very reliable and very easy to format (within the script) into a CSV file very suitable for import into a SQL database. Bravo! 

Apologies for the basic question, but I'm new to calling Java programs inside a script:

My bash script runs pretty slow (10 sec per PDF), primarily because it has to call tabula-java four times for each PDF (there are up to 4 different tables I need from each PDF). Currently, I'm just calling the JAR file:
`java -jar ~/unixstuff/tabula.jar -a 371.0,51.995,677.765,566.075 -p 1 $filename > tempfile`
That works great, but I'm looking for more speed so I'd prefer to avoid the overhead it imposes. I'd like to call the Java app directly.
**Question 1:** Am I correct in assuming I would see some speed-up if, instead, I unzipped the JAR and called the right class directly?
**Question 2:** How the heck do I do that??? I unzipped the JAR and put the CommandLineApp.class directory in my PATH, but when I make the call:
`java CommandLineApp -a 137.318,367.2,233.708,573.75 -p 1 $filename > tempfile`
I get the error:
`Exception in thread "main" java.lang.NoClassDefFoundError: CommandLineApp (wrong name: technology/tabula/CommandLineApp)`
I'm obviously screwing something up but, like I say, I'm a noob at calling Java apps from bash scripts. Help?

**Comment by jeremybmerrill** [comment]
Hi! There are a lot of possibilities depending on what you're most comfortable with. They all require scripting in some language. 

I'm afraid not: unzipping the JAR will not help. The slowdown is from starting up the JVM -- once per call of `java -jar`, so four times per PDF. You could write a small Java program to import Tabula and iterate over the contents of the script. That'd save you the startup time by only starting Tabula once, regardless of how many PDFs you're parsing.

Alternatively, you could try [tabula-extractor](https://www.github.com/tabulapdf/tabula-extractor), which is a JRuby wrapper for tabula-java. You'd have to write a Ruby script to do the same thing, but you'd still incur the cost of starting the JVM only once. (I'm most comfortable in Ruby, so this is what I would choose, but your skills and interests may be different.)

A third option would be to start the Tabula GUI and use it as an API. You still have to script this.

A fourth option that probably wouldn't work is to use Nailgun, which purports to solve this problem, but which I've never used.

Happy to continue to talk through the options...

**Comment by jazzido** [comment]
> A fourth option that probably wouldn't work is to use Nailgun, which purports to solve this problem, but which I've never used.

This is probably the best option, if you're executing `tabula-java` multiple times within the same bash script.

**Comment by jeremybmerrill** [comment]
@jazzido It looked complicated. Do you have an example?

**Comment by jazzido** [comment]
[drip](https://github.com/ninjudd/drip) is another better option:

```
drip -cp ./tabula-0.9.0-jar-with-dependencies.jar technology.tabula.CommandLineApp
```

**Comment by shaonds** [comment]
Is that possible to use tabula-java without bash script?
