### ISSUE TITLE
java.util.NoSuchElementException:null

### ISSUE THREAD

**Issue by samadrokzz** [tabulapdf/tabula-java#77]
i have an error while calling this 
getPage(path, page).getArea(area);

java.util.NoSuchElementException: null
    at java.util.ArrayList$Itr.next(Unknown Source)
    at java.util.Collections.min(Unknown Source)
    at technology.tabula.Page.getArea

**Comment by jazzido** [comment]
Hi @samadrokzz,

We need more details. A failing test case would be ideal.

Thanks.

**Comment by jeremybmerrill** [comment]
fixed via #131. fix will be in the next release.
