### ISSUE TITLE
Does tabula-java support table recognition in images(e.g., png, jpg), not just pdf?

### ISSUE THREAD

**Issue by johnny5550822** [tabulapdf/tabula-java#89]
_Sorry, I cannot find google group for tabulapdf, therefore I ask my question here. If there is a better place, please let me know._

Does tabula-java support table recognition in images(e.g., png, jpg), not just pdf? Also, is tabula-java commercial free?

**Comment by jazzido** [comment]
Hi @johnny5550822,

> Does tabula-java support table recognition in images(e.g., png, jpg), not just pdf? 
It doesn't.

> Also, is tabula-java commercial free?
Yes, it is released under the MIT license.
