### ISSUE TITLE
debug option from command line

### ISSUE THREAD

**Issue by pchowdhry** [tabulapdf/tabula-java#94]
Hi Guys is the debug option implemented? I pass in a -d and it doesn't seem to impact the processing.

**Comment by jeremybmerrill** [comment]
Doesn't look like it... @jazzido 

You can use the debug command like this `java -cp target/tabula-0.9.0-jar-with-dependencies.jar technology.tabula.debug.Debug test_1_s.pdf` -- it'll output an image of your document, with detected stuff (lines, tables, etc.) drawn on it

**Comment by Dietr1ch** [comment]
@jeremybmerrill I had the same thought at the beginning. The readme + `--help` suggests that running `java -jar target/tabula-0.9.1-jar-with-dependencies.jar  --guess -d  doc.pdf` would give you back the area.

Running `java -cp target/tabula-0.9.1-jar-with-dependencies.jar technology.tabula.debug.Debug  -a 0,0,100,100  doc.pdf`  was helpful, but I would not had guessed that it generated a jpg on the same directory, and as I was processing files on another directory, it could be easily unseen.
