### ISSUE TITLE
JSON output truncating

### ISSUE THREAD

**Issue by pchowdhry** [tabulapdf/tabula-java#95]
Hi Guys have you tested for large JSON outputs? I'm testing with some pretty large files, and the extraction runs, but my JSON output abruptly ends.

**Comment by jeremybmerrill** [comment]
Are you using one of the packaged (including Maven) versions, or building from master? I suspect this is the same problem as #68

**Comment by jeremybmerrill** [comment]
Which is all to say: I suspect if you rebuild from master (instructions in Readme), it will work correctly. Please give it a shot and let us know. If building from master does work, I'll ping whoever builds the project to rebuild it to fix this issue in Releases and in Maven.

**Comment by pchowdhry** [comment]
Thanks Jeremy, i'll give it a try.

**Comment by pchowdhry** [comment]
That worked, thanks.

**Comment by jeremybmerrill** [comment]
Glad to hear it. I'll figure out how to get a new build published...

Jeremy B. Merrill
