### ISSUE TITLE
Command line tool not extracting text that tabula can

### ISSUE THREAD

**Issue by pvabbvap** [tabulapdf/tabula-java#97]
I'm having an issue with a certain file, specifically these rows on this table:

![table](https://cloud.githubusercontent.com/assets/13327110/17515987/598504e0-5e6e-11e6-9fe1-63dd72d67d71.PNG)

When using tabula to extract the table, everything works fine, as seen below:

![table2](https://cloud.githubusercontent.com/assets/13327110/17516051/c07cfa7c-5e6e-11e6-80e7-16cfbf6be90b.PNG)

But using the command line (and the exact same coordinates), it comes out like this:

![table3](https://cloud.githubusercontent.com/assets/13327110/17516110/11dbe0fe-5e6f-11e6-90fd-b52f4fc35666.PNG)

I've been using the following command:
`>java -jar tabula-0.9.0-SNAPSHOT-jar-with-dependencies.jar -a 163.328,125.500,358.403,591.728 -p 1 -o a.csv file.pdf`

Is there anything I'm doing wrong, maybe not using the correct arguments or something?

**Comment by criztovyl** [comment]
Maybe `--spreadsheet` (`-r`)?

**Comment by pvabbvap** [comment]
That didn't work, but it led me to try using `-n`, which did. Thanks.

**Comment by criztovyl** [comment]
You're welcome, but if it's fixed you should close the issue ^^
