### ISSUE TITLE
Coordinates in PDF

### ISSUE THREAD

**Issue by saurabh** [tabulapdf/tabula-java#99]
Hi, how do you find coordinates in PDF file? which tool? what is the origin in PDF file (lower left/upper left)? Essentially there is a function `technology.tabula.Page.getText(technology.tabula.Rectangle)`. Can you please guide how to use it? In linux there is a tool called `pdftotext -bbox`; the cordinates that it finds are not compatible with Tabula.

Thanks in advance.
P.S. Is there a discussion forum somewhere for Tabula?

**Comment by jeremybmerrill** [comment]
I believe the upper-left is the (0,0) point. 

In short, I don't know of a great method for figuring out the coordinates. Probably the best way is to use the Tabula GUI web tool. The coordinates of your selection can be output by selecting the "Script" download option and -- I believe -- they're printed in the dev console.

No discussion forum, besides this.

**Comment by jazzido** [comment]
Hi @saurabh,

[This page on the wiki](https://github.com/tabulapdf/tabula-java/wiki/Using-the-command-line-tabula-extractor-tool) might have useful information.
